src/orgs/usa/data-model/objects/EmrServerInsuranceCompanyMetadata__c/EmrServerInsuranceCompanyMetadata__c.object-meta.xml
<CustomObject>
    <label>EMR Server Insurance Company Metadata</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Server Insurance Companies Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerInsuranceCompanyMetadata__c/fields/InsuranceCompanyInternalId__c.field-meta.xml
<CustomField>
    <fullName>InsuranceCompanyInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Insurance Company Internal Id</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/code/modules/artemis-rest-client/classes/models/ArtemisMetadataInsuranceCompanyRestModel.cls
/**
 * @description  : This class represents an insurance company metadata in the Artemis Rest API.
 * @author       : Ivo Rocha
 **/
public class ArtemisMetadataInsuranceCompanyRestModel extends EmrRestClient.RestModel {
	public String id { get; set; }
	public String name { get; set; }

	public ArtemisMetadataInsuranceCompanyRestModel() {
	}

	public EmrServerInsuranceCompanyMetadata__c toSObject() {
		return toSObject(null);
	}

	public EmrServerInsuranceCompanyMetadata__c toSObject(Id recordId) {
		EmrServerInsuranceCompanyMetadata__c insuranceCompanyMetadataRecord = new EmrServerInsuranceCompanyMetadata__c(Id = recordId);
		insuranceCompanyMetadataRecord.InsuranceCompanyInternalId__c = this.id;
		insuranceCompanyMetadataRecord.Name = this.name;
		return insuranceCompanyMetadataRecord;
	}

	public Boolean equals(EmrServerInsuranceCompanyMetadata__c insuranceCompanyMetadataRecord) {
		return insuranceCompanyMetadataRecord != null &&
			this.id == insuranceCompanyMetadataRecord.InsuranceCompanyInternalId__c &&
			this.name == insuranceCompanyMetadataRecord.Name;
	}
}