src/orgs/usa/data-model/objects/ArtemisChangeEvent__e/ArtemisChangeEvent__e.object-meta.xml
<CustomObject>
    <description>Platform Event object used to receive published events by the Artemis EMR servers, whenever modifications happen in the system and changes must be communicated back to Salesforce.</description>
    <label>Artemis Change Event</label>
    <pluralLabel>Artemis Change Events</pluralLabel>
</CustomObject>

src/orgs/usa/data-model/objects/ArtemisChangeEvent__e/fields/ArtemisServer__c.field-meta.xml
<CustomField>
    <fullName>ArtemisServer__c</fullName>
    <description>Defines the source Artemis server instance this event was generated from. Expected values are: BOSNY, BOSNE and BOSNC</description>
    <label>Artemis Server</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/ArtemisChangeEvent__e/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>The type of event that affected the resource. Expects values like: create, update and delete.</description>
    <label>Event</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/ArtemisChangeEvent__e/fields/ResourceIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ResourceIdentifier__c</fullName>
    <description>External identifier of the affected resource.</description>
    <label>Resource Identifier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/ArtemisChangeEvent__e/fields/ResourceName__c.field-meta.xml
<CustomField>
    <fullName>ResourceName__c</fullName>
    <description>Name of the affected resource. Expects names like: Patient, Provider, Location, Appointment, ...</description>
    <label>Resource type name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerInboundRequest__c/EmrServerInboundRequest__c.object-meta.xml
<CustomObject>
    <label>EMR Server Inbound Request</label>
    <nameField>
        <displayFormat>EIR-{0000}</displayFormat>
        <label>EMR Server Inbound Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Inbound Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/code/modules/artemis-inbound-events-intake/classes/tests/FlowAction_ArtemisChangeEvntsIntakerTest.cls
/**
 * @description       : Unit tests for the FlowAction_ArtemisChangeEventsIntaker class.
 * @author            : Ivo Rocha
 * @testSuite         : ArtemisEventsIntake
 **/
@isTest
private class FlowAction_ArtemisChangeEvntsIntakerTest {
	@TestSetup
	static void makeData() {
		ArtemisRestClientTest.makeData();
	}

	@isTest
	static void testProcessArtemisChangeEvent() {
		Test.setMock(HttpCalloutMock.class, HttpMocks.config());

		ArtemisChangeEvent__e event = new ArtemisChangeEvent__e(
			ArtemisServer__c = 'Artemis EMR',
			Event__c = 'create',
			ResourceName__c = 'patient',
			ResourceIdentifier__c = '1234567890'
		);

		Test.startTest();
		FlowAction_ArtemisChangeEventsIntaker.processArtemisChangeEvent(new List<ArtemisChangeEvent__e>{ event });
		Test.stopTest();

		Assert.areEqual(1, [SELECT COUNT() FROM EmrServerInboundRequest__c], 'There should be one inbound request logged');
	}
}