src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/ApiSchemaSpec__c.field-meta.xml
<CustomField>
    <fullName>ApiSchemaSpec__c</fullName>
    <description>Specifies the API Schema Specifications. Will map to a target class. Eg. if spec is Artemis then a class ArtemisRestClient must exist</description>
    <label>API Schema Spec</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Artemis</fullName>
                <default>true</default>
                <label>Artemis</label>
            </value>
            <value>
                <fullName>Sivis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/InboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>InboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for inbound requests in days. This setting determines how long inbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of inbound requests.</description>
    <inlineHelpText>The number of days to retain logs. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Inbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description>API Name of the Named Credential associated with the EMR Server record, used for authentication purposes.</description>
    <inlineHelpText>Enter the Developer API Name of the Named Credential that will be used for authentication with the EMR Server.</inlineHelpText>
    <label>Named Credential</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/OutboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>OutboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for outbound requests in days. This setting determines how long outbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of outbound requests.</description>
    <inlineHelpText>The number of days to retain requests. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Outbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/TimeoutRequestPeriod__c.field-meta.xml
<CustomField>
    <fullName>TimeoutRequestPeriod__c</fullName>
    <defaultValue>60000</defaultValue>
    <inlineHelpText>In milliseconds</inlineHelpText>
    <label>Timeout request after (ms)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/EmrServerAccountReference__c.object-meta.xml
<CustomObject>
    <label>EMR Server Account Reference</label>
    <nameField>
        <displayFormat>ESAR-{0000}</displayFormat>
        <label>EMR Server Account Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Account References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>EmrServerAccountRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipName>EmrServerAccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/fields/IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

src/orgs/usa/code/modules/artemis-data-processors/classes/tests/ArtemisPatientsDataProcessorTest.cls
/**
 * @description  : Unit tests for ArtemisPatientsDataProcessor
 * @author 	     : Ivo Rocha
 * @testSuite    : ArtemisDataProcessors
 **/
@isTest
private class ArtemisPatientsDataProcessorTest {
	@TestSetup
	static void makeData() {
		EmrServer__c emrServer = new EmrServer__c(
			Name = 'XPTO',
			ApiSchemaSpec__c = 'XPTO',
			NamedCredential__c = 'https://unit.xpto.test',
			TimeoutRequestPeriod__c = 50000,
			InboundRequestsRetentionPeriod__c = 10,
			OutboundRequestsRetentionPeriod__c = 15
		);
		insert emrServer;

		Account patient = new Account(RecordTypeId = RecordTypes.ACCOUNT_PATIENT.id, FirstName = 'Foo', LastName = 'Bar');
		insert patient;

		EmrServerAccountReference__c ermPatientReference = new EmrServerAccountReference__c(
			EmrServer__c = emrServer.Id,
			Account__c = patient.Id,
			Identifier__c = '12345',
			IsPrimary__c = true
		);
		insert ermPatientReference;
	}

	@isTest
	static void shouldUpdateExistingPatient() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');

		ArtemisPatientRestModel payloadModel = new ArtemisPatientRestModel();
		payloadModel.id = '12345';
		payloadModel.salutation = 'Mr.';
		payloadModel.prefersName = 'Foo';
		payloadModel.firstName = 'Foo';
		payloadModel.middleName = 'Bar';
		payloadModel.lastName = 'Bar';
		payloadModel.suffix = 'Jr.';
		payloadModel.socialSecurityNumber = '123456789';
		payloadModel.dateOfBirth = Date.newInstance(1990, 1, 1);
		payloadModel.patientType = 'Patient';

		ArtemisPatientsDataProcessor processor = new ArtemisPatientsDataProcessor();
		processor.add(emrServer, payloadModel);

		Test.startTest();
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		Assert.isNotNull(results, 'Results should not be null');
		Assert.areEqual(1, results.size(), 'There should be one result');
		Assert.isTrue(results[0].isSuccess(), 'The result should be successful');

		Assert.areEqual(1, [SELECT COUNT() FROM Account WHERE RecordTypeId = :RecordTypes.ACCOUNT_PATIENT.id], 'There should be one patient in the database');
		EmrServerAccountReference__c ermPatientReference = (EmrServerAccountReference__c) new EmrServerAccountReferenceQuery()
			.byEmrServerId(emrServer.emrServerId)
			.byIdentifier(payloadModel.id)
			.getFirstOrNull();

		Account patient = (Account) new PatientQuery().withErmServerReference(ermPatientReference).getFirstOrNull();
		Assert.areEqual(payloadModel.firstName, patient.FirstName, 'The patient should have the correct first name');
		Assert.areEqual(payloadModel.lastName, patient.LastName, 'The patient should have the correct last name');
		Assert.areEqual(payloadModel.salutation, patient.Salutation, 'The patient should have the correct salutation');
		Assert.areEqual(payloadModel.prefersName, patient.PreferredFirstName__pc, 'The patient should have the correct preferred first name');
		Assert.areEqual(payloadModel.middleName, patient.MiddleName, 'The patient should have the correct middle name');
		Assert.areEqual(payloadModel.suffix, patient.Suffix, 'The patient should have the correct suffix');
		Assert.areEqual(payloadModel.socialSecurityNumber, patient.SocialSecurityNumber__pc, 'The patient should have the correct social security number');
		Assert.areEqual(payloadModel.dateOfBirth, patient.PersonBirthdate, 'The patient should have the correct date of birth');
		//Assert.areEqual(payloadModel.patientType, patient.PersonPatientType__pc, 'The patient should have the correct patient type');
	}

	//TODO: test for new patient creation when respective logic is implemented in the processor
}