src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/ApiSchemaSpec__c.field-meta.xml
<CustomField>
    <fullName>ApiSchemaSpec__c</fullName>
    <description>Specifies the API Schema Specifications. Will map to a target class. Eg. if spec is Artemis then a class ArtemisRestClient must exist</description>
    <label>API Schema Spec</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Artemis</fullName>
                <default>true</default>
                <label>Artemis</label>
            </value>
            <value>
                <fullName>Sivis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/InboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>InboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for inbound requests in days. This setting determines how long inbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of inbound requests.</description>
    <inlineHelpText>The number of days to retain logs. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Inbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description>API Name of the Named Credential associated with the EMR Server record, used for authentication purposes.</description>
    <inlineHelpText>Enter the Developer API Name of the Named Credential that will be used for authentication with the EMR Server.</inlineHelpText>
    <label>Named Credential</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/OutboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>OutboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for outbound requests in days. This setting determines how long outbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of outbound requests.</description>
    <inlineHelpText>The number of days to retain requests. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Outbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/TimeoutRequestPeriod__c.field-meta.xml
<CustomField>
    <fullName>TimeoutRequestPeriod__c</fullName>
    <defaultValue>60000</defaultValue>
    <inlineHelpText>In milliseconds</inlineHelpText>
    <label>Timeout request after (ms)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/classes/tests/EmrRestClientFactoryTest.cls
/**
 * @description  : This is a test implementation of the EmrRestClientFactory class.
 * @author       : Ivo Rocha
 * @testSuites   : EMRServerMgmt
 **/
@isTest
private class EmrRestClientFactoryTest {
	@TestSetup
	public static void makeData() {
		insert new EmrServer__c(
			Name = 'XPTO EMR',
			ApiSchemaSpec__c = 'EmrRestClientFactoryTest.TestSchemaSpec', //Schema defined in the bottom of this class
			NamedCredential__c = 'https://unit.xpto.test'
		);
	}

	private static EmrServer__c getTestEmrServerRecord() {
		return [
			SELECT Id, Name, ApiSchemaSpec__c, TimeoutRequestPeriod__c, InboundRequestsRetentionPeriod__c, OutboundRequestsRetentionPeriod__c
			FROM EmrServer__c
			LIMIT 1
		];
	}

	@isTest
	static void shouldFailToInstantiateNotImplementedSchema() {
		EmrServer__c emrServerRecord = getTestEmrServerRecord();
		emrServerRecord.ApiSchemaSpec__c = 'NotImplementedSchema';
		update emrServerRecord;

		Test.startTest();
		try {
			EmrRestClientFactory.getRestClientInstance(emrServerRecord.Id);
			Assert.fail('Expected EmrRestClientException but got none');
		} catch (EmrRestClientException ex) {
			Assert.isTrue(ex.getMessage().contains('Invalid API Schema Spec'), 'Expected exception error message to contain "Invalid API Schema Spec"');
		} catch (Exception ex) {
			Assert.fail('Expected EmrRestClientException but got: ' + ex.getMessage());
		}
		Test.stopTest();
	}

	@isTest
	static void shouldInstantiateImplementedSchema() {
		EmrServer__c emrServerRecord = getTestEmrServerRecord();

		Test.startTest();
		try {
			EmrRestClient testRestClientIntance = EmrRestClientFactory.getRestClientInstance(emrServerRecord.Id);
			Assert.isNotNull(testRestClientIntance, 'Expected testRestClientIntance to be not null');
		} catch (Exception ex) {
			Assert.fail('No expected exception but got: ' + ex.getMessage());
		}
		Test.stopTest();
	}

	@isTest
	static void shoulAllowToBuildACalloutForClient() {
		Test.setMock(
			HttpCalloutMock.class,
			HttpMocks.config().mock('testEndpoint', 'GET', 'https://unit.xpto.test/api/v1/testEndpoint', HttpMocks.text(200, 'OK', '{"status":"OK"}'))
		);

		EmrServer__c emrServerRecord = getTestEmrServerRecord();

		Test.startTest();

		EmrRestClient testRestClientIntance = EmrRestClientFactory.getRestClientInstance(emrServerRecord.Id);
		Assert.isNotNull(testRestClientIntance, 'Expected testRestClientIntance to be not null');

		Callout simpleCallout = testRestClientIntance.buildCallout();
		Assert.isNotNull(simpleCallout, 'Expected callout to be not null');

		simpleCallout.setMethod('GET');
		simpleCallout.setEndpoint('/api/v1/testEndpoint');
		simpleCallout.setResponseType(TestReponseModel.class);

		TestReponseModel response = (TestReponseModel) simpleCallout.execute();
		Assert.isNotNull(response, 'Expected response to be not null');
		Assert.isTrue(response.status == 'OK', 'Expected response status to be OK');

		Test.stopTest();
	}

	/**
	 * @description  : This is a test implementation of the EmrRestClient class for testing purposes.
	 */
	public class TestSchemaSpecRestClient extends EmrRestClient {
	}

	public class TestReponseModel extends EmrRestClient.RestModel {
		public String status;
		public TestReponseModel(String status) {
			this.status = status;
		}
	}
}