src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/EmrServerAccountReference__c.object-meta.xml
<CustomObject>
    <label>EMR Server Account Reference</label>
    <nameField>
        <displayFormat>ESAR-{0000}</displayFormat>
        <label>EMR Server Account Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Account References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>EmrServerAccountRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipName>EmrServerAccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/fields/IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/classes/query-selectors/EmrServerAccountReferenceQuery.cls
/**
 * @description  : Query object for EmrServerAccountReference__c records.
 * @author       : Ivo Rocha
 **/
public with sharing class EmrServerAccountReferenceQuery extends QueryObject {
	public EmrServerAccountReferenceQuery() {
		super(EmrServerAccountReference__c.SObjectType);
		withAllFields();
		withFields('EmrServer__r.Name');
	}

	public EmrServerAccountReferenceQuery byAccountId(Id accountId) {
		return byAccountId(new Set<Id>{ accountId });
	}

	public EmrServerAccountReferenceQuery byAccountId(Set<Id> accountIds) {
		return (EmrServerAccountReferenceQuery) byField(EmrServerAccountReference__c.Account__c, 'IN', accountIds);
	}

	public EmrServerAccountReferenceQuery byEmrServerId(Id emrServerId) {
		return byEmrServerId(new Set<Id>{ emrServerId });
	}

	public EmrServerAccountReferenceQuery byEmrServerId(Set<Id> emrServerIds) {
		return (EmrServerAccountReferenceQuery) byField(EmrServerAccountReference__c.EmrServer__c, 'IN', emrServerIds);
	}

	public EmrServerAccountReferenceQuery byIdentifier(String identifier) {
		return byIdentifier(new Set<String>{ identifier });
	}

	public EmrServerAccountReferenceQuery byIdentifier(Set<String> identifiers) {
		return (EmrServerAccountReferenceQuery) byField(EmrServerAccountReference__c.Identifier__c, 'IN', identifiers);
	}

	public EmrServerAccountReferenceQuery byIsPrimary(Boolean isPrimary) {
		return (EmrServerAccountReferenceQuery) byField(EmrServerAccountReference__c.IsPrimary__c, '=', isPrimary);
	}
}