src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/ApiSchemaSpec__c.field-meta.xml
<CustomField>
    <fullName>ApiSchemaSpec__c</fullName>
    <description>Specifies the API Schema Specifications. Will map to a target class. Eg. if spec is Artemis then a class ArtemisRestClient must exist</description>
    <label>API Schema Spec</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Artemis</fullName>
                <default>true</default>
                <label>Artemis</label>
            </value>
            <value>
                <fullName>Sivis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/InboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>InboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for inbound requests in days. This setting determines how long inbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of inbound requests.</description>
    <inlineHelpText>The number of days to retain logs. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Inbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description>API Name of the Named Credential associated with the EMR Server record, used for authentication purposes.</description>
    <inlineHelpText>Enter the Developer API Name of the Named Credential that will be used for authentication with the EMR Server.</inlineHelpText>
    <label>Named Credential</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/OutboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>OutboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for outbound requests in days. This setting determines how long outbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of outbound requests.</description>
    <inlineHelpText>The number of days to retain requests. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Outbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/TimeoutRequestPeriod__c.field-meta.xml
<CustomField>
    <fullName>TimeoutRequestPeriod__c</fullName>
    <defaultValue>60000</defaultValue>
    <inlineHelpText>In milliseconds</inlineHelpText>
    <label>Timeout request after (ms)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/classes/tests/EmrServerAbstractDataProcessorTest.cls
/**
 * @description  : Unit tests for the EmrServerAbstractDataProcessor class.
 * @author       : Ivo Rocha
 * @testSuites   : EMRServerMgmt
 **/
@isTest
private class EmrServerAbstractDataProcessorTest {
	@TestSetup
	static void makeData() {
		insert new EmrServer__c(
			Name = 'XPTO',
			ApiSchemaSpec__c = 'XPTO',
			NamedCredential__c = 'https://unit.xpto.test',
			TimeoutRequestPeriod__c = 50000,
			InboundRequestsRetentionPeriod__c = 10,
			OutboundRequestsRetentionPeriod__c = 15
		);
	}

	@isTest
	static void testSuccessfullExecutionWithOneRequest() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');
		Assert.isNotNull(emrServer, 'EmrServer instance should not be null');

		Test.startTest();
		TestImplEmrServerAbstractDataProcessor processor = new TestImplEmrServerAbstractDataProcessor();
		processor.add(emrServer, new EmrRestClient.RestModel());
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		Assert.isNotNull(results, 'Results should not be null');
		Assert.areEqual(1, results.size(), 'There should be one result');
		Assert.isTrue(results[0].isSuccess(), 'Result should be successful');
	}

	@isTest
	static void testSuccessfullExecutionWithMultipleRequests() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');

		Test.startTest();
		TestImplEmrServerAbstractDataProcessor processor = new TestImplEmrServerAbstractDataProcessor();
		processor.add(emrServer, new List<EmrRestClient.RestModel>{ new EmrRestClient.RestModel(), new EmrRestClient.RestModel() });
		processor.add(emrServer, new EmrRestClient.RestModel(), 'Additional Context');
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		Assert.isNotNull(results, 'Results should not be null');
		Assert.areEqual(3, results.size(), 'There should be three results');
		Assert.isTrue(results[0].isSuccess(), 'First result should be successful');
		Assert.isTrue(results[1].isSuccess(), 'Second result should be successful');
		Assert.isTrue(results[2].isSuccess(), 'Third result should be successful');
	}

	@isTest
	static void testEmptyRequestList() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');

		Test.startTest();
		TestImplEmrServerAbstractDataProcessor processor = new TestImplEmrServerAbstractDataProcessor();
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		Assert.isNotNull(results, 'Results should not be null');
		Assert.areEqual(0, results.size(), 'There should be no results');
	}

	@isTest
	static void testExceptionHandling() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');

		Test.startTest();
		TestImplWithExceptionEmrServerAbstractDataProcessor processor = new TestImplWithExceptionEmrServerAbstractDataProcessor();
		processor.add(emrServer, new EmrRestClient.RestModel());
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		Assert.isNotNull(results, 'Results should not be null');
		Assert.areEqual(1, results.size(), 'There should be one result');
		Assert.isFalse(results[0].isSuccess(), 'Result should not be successful');
		Assert.isNotNull(results[0].getMessage(), 'Message should not be null');
		Assert.isTrue(results[0].getMessage().contains('Test exception'), 'Message should match');
	}

	// Testable implementation of the abstract class
	private class TestImplEmrServerAbstractDataProcessor extends EmrServerAbstractDataProcessor {
		public TestImplEmrServerAbstractDataProcessor() {
			super();
		}

		Object prepare(Map<EmrServer, List<EmrRestClient.RestModel>> payloadsByServer, List<EmrServer> servers, List<EmrRestClient.RestModel> payloads) {
			return new Map<Object, Object>();
		}

		void handle(EmrRestClient.RestModel payload, EmrServerDataProcessRequestContext context) {
		}
	}

	private class TestImplWithExceptionEmrServerAbstractDataProcessor extends EmrServerAbstractDataProcessor {
		public TestImplWithExceptionEmrServerAbstractDataProcessor() {
			super();
		}

		Object prepare(Map<EmrServer, List<EmrRestClient.RestModel>> payloadsByServer, List<EmrServer> servers, List<EmrRestClient.RestModel> payloads) {
			return new Map<Object, Object>();
		}

		void handle(EmrRestClient.RestModel payload, EmrServerDataProcessRequestContext context) {
			throw new EmrServerDataProcessException('Test exception');
		}
	}
}