src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/ApiSchemaSpec__c.field-meta.xml
<CustomField>
    <fullName>ApiSchemaSpec__c</fullName>
    <description>Specifies the API Schema Specifications. Will map to a target class. Eg. if spec is Artemis then a class ArtemisRestClient must exist</description>
    <label>API Schema Spec</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Artemis</fullName>
                <default>true</default>
                <label>Artemis</label>
            </value>
            <value>
                <fullName>Sivis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/InboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>InboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for inbound requests in days. This setting determines how long inbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of inbound requests.</description>
    <inlineHelpText>The number of days to retain logs. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Inbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description>API Name of the Named Credential associated with the EMR Server record, used for authentication purposes.</description>
    <inlineHelpText>Enter the Developer API Name of the Named Credential that will be used for authentication with the EMR Server.</inlineHelpText>
    <label>Named Credential</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/OutboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>OutboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for outbound requests in days. This setting determines how long outbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of outbound requests.</description>
    <inlineHelpText>The number of days to retain requests. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Outbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/TimeoutRequestPeriod__c.field-meta.xml
<CustomField>
    <fullName>TimeoutRequestPeriod__c</fullName>
    <defaultValue>60000</defaultValue>
    <inlineHelpText>In milliseconds</inlineHelpText>
    <label>Timeout request after (ms)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/EmrServerReferralSourceMetadata__c.object-meta.xml
<CustomObject>
    <label>EMR Server Referral Source Metadata</label>
    <nameField>
        <displayFormat>ESRS-{0000}</displayFormat>
        <label>EMR Server Referral Source Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Referral Sources Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>EMR Server Referral Sources Metadata</relationshipLabel>
    <relationshipName>EmrServerReferralSourcesMetadata</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferralCategory__c.field-meta.xml
<CustomField>
    <fullName>ReferralCategory__c</fullName>
    <label>Referral Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferralCategoryInternalId__c.field-meta.xml
<CustomField>
    <fullName>ReferralCategoryInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Referral Category Internal Id</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferralSourceInternalId__c.field-meta.xml
<CustomField>
    <fullName>ReferralSourceInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Referral Source Internal Id (REF)</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferredBy__c.field-meta.xml
<CustomField>
    <fullName>ReferredBy__c</fullName>
    <label>Referred By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/code/modules/artemis-data-processors/classes/tests/ArtemisMetaRefSourcesDataProcessorTest.cls
/**
 * @description  : Unit tests for ArtemisMetaReferralSourcesDataProcessor
 * @author       : Ivo Rocha
 * @testSuite    : ArtemisDataProcessors
 **/
@isTest
private class ArtemisMetaRefSourcesDataProcessorTest {
	@TestSetup
	static void makeData() {
		insert new EmrServer__c(
			Name = 'XPTO',
			ApiSchemaSpec__c = 'XPTO',
			NamedCredential__c = 'https://unit.xpto.test',
			TimeoutRequestPeriod__c = 50000,
			InboundRequestsRetentionPeriod__c = 10,
			OutboundRequestsRetentionPeriod__c = 15
		);
	}

	@isTest
	static void shouldProcessPayloadForNewReferralSource() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');

		ArtemisMetadataReferralSourceRestModel payloadModel = new ArtemisMetadataReferralSourceRestModel();
		payloadModel.id = '12345';
		payloadModel.refBy = 'John Doe';
		payloadModel.refCat = new ArtemisMetadataReferralSourceRestModel.ReferenceCategory();
		payloadModel.refCat.id = '67890';
		payloadModel.refCat.name = 'Doctor';

		ArtemisMetaReferralSourcesDataProcessor processor = new ArtemisMetaReferralSourcesDataProcessor();
		processor.add(emrServer, payloadModel);

		Test.startTest();
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		Assert.isNotNull(results, 'Results should not be null');
		Assert.areEqual(1, results.size(), 'There should be one result');
		Assert.isTrue(results[0].isSuccess(), 'Result should be successful');

		Assert.areEqual(1, [SELECT COUNT() FROM EmrServerReferralSourceMetadata__c], 'There should be one record in the database');
	}

	@isTest
	static void shouldProcessPayloadForExistingReferralSource() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');

		// Create an existing record
		EmrServerReferralSourceMetadata__c existingRecord = new EmrServerReferralSourceMetadata__c(
			ReferralSourceInternalId__c = '12345',
			ReferredBy__c = 'NewYorkMag',
			ReferralCategory__c = 'Magazine',
			ReferralCategoryInternalId__c = '67890',
			EmrServer__c = emrServer.emrServerId
		);
		insert existingRecord;

		// Create a new payload with the same ID but different values
		ArtemisMetadataReferralSourceRestModel payloadModel = new ArtemisMetadataReferralSourceRestModel();
		payloadModel.id = '12345';
		payloadModel.refBy = 'NewYorkMagazine'; //Different value
		payloadModel.refCat = new ArtemisMetadataReferralSourceRestModel.ReferenceCategory();
		payloadModel.refCat.id = '67890';
		payloadModel.refCat.name = 'Magazine';

		ArtemisMetaReferralSourcesDataProcessor processor = new ArtemisMetaReferralSourcesDataProcessor();
		processor.add(emrServer, payloadModel);

		Test.startTest();
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		Assert.isNotNull(results, 'Results should not be null');
		Assert.areEqual(1, results.size(), 'There should be one result');
		Assert.isTrue(results[0].isSuccess(), 'Result should be successful');
		Assert.areEqual(1, [SELECT COUNT() FROM EmrServerReferralSourceMetadata__c], 'There should be one record in the database');
		EmrServerReferralSourceMetadata__c updatedRecord = [
			SELECT Id, ReferredBy__c
			FROM EmrServerReferralSourceMetadata__c
			WHERE Id = :existingRecord.Id
		];
		Assert.areEqual('NewYorkMagazine', updatedRecord.ReferredBy__c, 'The record should be updated with the new name');
	}
}