src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/EmrServerReferralSourceMetadata__c.object-meta.xml
<CustomObject>
    <label>EMR Server Referral Source Metadata</label>
    <nameField>
        <displayFormat>ESRS-{0000}</displayFormat>
        <label>EMR Server Referral Source Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Referral Sources Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>EMR Server Referral Sources Metadata</relationshipLabel>
    <relationshipName>EmrServerReferralSourcesMetadata</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferralSourceInternalId__c.field-meta.xml
<CustomField>
    <fullName>ReferralSourceInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Referral Source Internal Id (REF)</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/code/modules/artemis-data-processors/classes/ArtemisMetaReferralSourcesDataProcessor.cls
/**
 * @description  : This class is responsible for processing Referral Source metadata from the Artemis EMR system.
 * @author       : Ivo Rocha
 * @testSuite    : ArtemisDataProcessors
 **/
public inherited sharing class ArtemisMetaReferralSourcesDataProcessor extends EmrServerAbstractDataProcessor {
	public ArtemisMetaReferralSourcesDataProcessor() {
		super();
	}

	Object prepare(Map<EmrServer, List<EmrRestClient.RestModel>> payloadsByServer, List<EmrServer> servers, List<EmrRestClient.RestModel> payloads) {
		Set<String> metaIds = Collection.of(payloads).collect(new MetaReferralSourceIdMapper()).getSetString();
		Set<Id> emrServerIds = Collection.of(servers).collect(new EmrServerIdMapper()).getSetId();

		Map<String, EmrServerReferralSourceMetadata__c> existingReferralSourceMetadataByReference = (Map<String, EmrServerReferralSourceMetadata__c>) new EmrServerReferralSourceMetadataQuery()
			.byEmrServerId(emrServerIds)
			.byExternalId(metaIds)
			.getMapByString(EmrServerReferralSourceMetadata__c.ReferralSourceInternalId__c);

		MetaReferralSourcesPreparedData result = new MetaReferralSourcesPreparedData();
		result.existingReferralSourceMetadataByReference = existingReferralSourceMetadataByReference;
		return result;
	}

	void handle(EmrRestClient.RestModel payload, EmrServerDataProcessRequestContext context) {
		MetaReferralSourcesPreparedData preparedData = (MetaReferralSourcesPreparedData) context.preparedData;
		ArtemisMetadataReferralSourceRestModel metaReferralSourcePayload = (ArtemisMetadataReferralSourceRestModel) payload;

		EmrServerReferralSourceMetadata__c existingReferralSourceMetadataByReference = preparedData.existingReferralSourceMetadataByReference.get(
			metaReferralSourcePayload.id
		);

		if (existingReferralSourceMetadataByReference != null && metaReferralSourcePayload.equals(existingReferralSourceMetadataByReference)) {
			//Ref. Source metadata already exists and there is no changes
			return;
		}

		EmrServerReferralSourceMetadata__c referralSourceRecord = metaReferralSourcePayload.toSObject(existingReferralSourceMetadataByReference?.Id);
		referralSourceRecord.EmrServer__c = context.sourceServer.emrServerId;

		DatabaseService databaseService = new DatabaseService().asSystemWithoutSharing();
		databaseService.upsertRecord(referralSourceRecord, EmrServerReferralSourceMetadata__c.Id);
	}

	private class MetaReferralSourcesPreparedData {
		public Map<String, EmrServerReferralSourceMetadata__c> existingReferralSourceMetadataByReference { get; set; }
	}

	private class MetaReferralSourceIdMapper implements Collection.Mapper {
		public Object value(Object item) {
			return ((ArtemisMetadataReferralSourceRestModel) item).id;
		}

		public Type valueType() {
			return String.class;
		}
	}
}