src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerInsuranceCompanyMetadata__c/EmrServerInsuranceCompanyMetadata__c.object-meta.xml
<CustomObject>
    <label>EMR Server Insurance Company Metadata</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Server Insurance Companies Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerInsuranceCompanyMetadata__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>EMR Server Insurance Companies Metadata</relationshipLabel>
    <relationshipName>EmrServerInsuranceCompaniesMetadata</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerInsuranceCompanyMetadata__c/fields/InsuranceCompanyInternalId__c.field-meta.xml
<CustomField>
    <fullName>InsuranceCompanyInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Insurance Company Internal Id</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/PatientServerProfile__c/PatientServerProfile__c.object-meta.xml
<CustomObject>
    <label>Patient Server Profile</label>
    <nameField>
        <displayFormat>PSP-{0000}</displayFormat>
        <label>Patient Server Profile #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Server Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/PatientServerProfile__c/fields/ArtemisPatientId__c.field-meta.xml
<CustomField>
    <fullName>ArtemisPatientId__c</fullName>
    <externalId>true</externalId>
    <label>Artemis Patient Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/PatientServerProfile__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>Patient Server Profiles</relationshipLabel>
    <relationshipName>PatientServerProfiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/data-model/objects/PatientServerProfile__c/fields/PrimaryInsuranceArtemisMetadata__c.field-meta.xml
<CustomField>
    <fullName>PrimaryInsuranceArtemisMetadata__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Insurance Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EmrServerInsuranceCompanyMetadata__c.EmrServer__c</field>
            <operation>equals</operation>
            <valueField>$Source.EmrServer__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>EmrServerInsuranceCompanyMetadata__c</referenceTo>
    <relationshipLabel>Patient Server Profiles (Primary Insurance)</relationshipLabel>
    <relationshipName>PrimaryInsurancePatientServerProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/PatientServerProfile__c/fields/SecondaryInsuranceArtemisMetadata__c.field-meta.xml
<CustomField>
    <fullName>SecondaryInsuranceArtemisMetadata__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Insurance Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EmrServerInsuranceCompanyMetadata__c.EmrServer__c</field>
            <operation>equals</operation>
            <valueField>$Source.EmrServer__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>EmrServerInsuranceCompanyMetadata__c</referenceTo>
    <relationshipLabel>Patient Server Profiles (Secondary Insurance)</relationshipLabel>
    <relationshipName>SecondaryInsurancePatientServerProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/PatientServerProfile__c/fields/TertiaryInsuranceArtemisMetadata__c.field-meta.xml
<CustomField>
    <fullName>TertiaryInsuranceArtemisMetadata__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tertiary Insurance Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EmrServerInsuranceCompanyMetadata__c.EmrServer__c</field>
            <operation>equals</operation>
            <valueField>$Source.EmrServer__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>EmrServerInsuranceCompanyMetadata__c</referenceTo>
    <relationshipLabel>Patient Server Profiles (Tertiary Insurance)</relationshipLabel>
    <relationshipName>TertiaryInsurancePatientServerProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/code/query-selectors/classes/PatientServerProfileQuery.cls
/**
 * @description  : Query object for Patient Server Profile records.
 * @author       : Ivo Rocha
 **/
public inherited sharing class PatientServerProfileQuery extends QueryObject {
	public PatientServerProfileQuery() {
		super(PatientServerProfile__c.SObjectType);
		withAllFields();
		withFields(
			new List<String>{
				'PrimaryInsuranceArtemisMetadata__r.InsuranceCompanyInternalId__c',
				'SecondaryInsuranceArtemisMetadata__r.InsuranceCompanyInternalId__c',
				'TertiaryInsuranceArtemisMetadata__r.InsuranceCompanyInternalId__c'
			}
		);
	}

	public PatientServerProfileQuery byEmrServerId(Id emrServerId) {
		return byEmrServerId(new Set<Id>{ emrServerId });
	}

	public PatientServerProfileQuery byEmrServerId(Set<Id> emrServerIds) {
		return (PatientServerProfileQuery) byField(PatientServerProfile__c.EmrServer__c, 'IN', emrServerIds);
	}

	public PatientServerProfileQuery byExternalId(String externalId) {
		return byExternalId(new Set<String>{ externalId });
	}

	public PatientServerProfileQuery byExternalId(Set<String> externalIds) {
		return (PatientServerProfileQuery) byField(PatientServerProfile__c.ArtemisPatientId__c, 'IN', externalIds);
	}
}