src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/EmrServerReferralSourceMetadata__c.object-meta.xml
<CustomObject>
    <label>EMR Server Referral Source Metadata</label>
    <nameField>
        <displayFormat>ESRS-{0000}</displayFormat>
        <label>EMR Server Referral Source Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Referral Sources Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>EMR Server Referral Sources Metadata</relationshipLabel>
    <relationshipName>EmrServerReferralSourcesMetadata</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferralCategory__c.field-meta.xml
<CustomField>
    <fullName>ReferralCategory__c</fullName>
    <label>Referral Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferralCategoryInternalId__c.field-meta.xml
<CustomField>
    <fullName>ReferralCategoryInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Referral Category Internal Id</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferralSourceInternalId__c.field-meta.xml
<CustomField>
    <fullName>ReferralSourceInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Referral Source Internal Id (REF)</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferredBy__c.field-meta.xml
<CustomField>
    <fullName>ReferredBy__c</fullName>
    <label>Referred By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/code/query-selectors/classes/EmrServerReferralSourceMetadataQuery.cls
/**
 * @description  : This class is used to query the EmrServerReferralSourceMetadata__c object.
 * @author       : Ivo Rocha
 **/
public inherited sharing class EmrServerReferralSourceMetadataQuery extends QueryObject {
	public EmrServerReferralSourceMetadataQuery() {
		super(
			new List<SObjectField>{
				EmrServerReferralSourceMetadata__c.Id,
				EmrServerReferralSourceMetadata__c.EmrServer__c,
				EmrServerReferralSourceMetadata__c.ReferralCategory__c,
				EmrServerReferralSourceMetadata__c.ReferralCategoryInternalId__c,
				EmrServerReferralSourceMetadata__c.ReferralSourceInternalId__c,
				EmrServerReferralSourceMetadata__c.ReferredBy__c
			},
			EmrServerReferralSourceMetadata__c.SObjectType
		);
	}

	public EmrServerReferralSourceMetadataQuery byEmrServerId(Id emrServerId) {
		return byEmrServerId(new Set<Id>{ emrServerId });
	}

	public EmrServerReferralSourceMetadataQuery byEmrServerId(Set<Id> emrServerIds) {
		return (EmrServerReferralSourceMetadataQuery) byField(EmrServerReferralSourceMetadata__c.EmrServer__c, 'IN', emrServerIds);
	}

	public EmrServerReferralSourceMetadataQuery byExternalId(String externalId) {
		return byExternalId(new Set<String>{ externalId });
	}

	public EmrServerReferralSourceMetadataQuery byExternalId(Set<String> externalIds) {
		return (EmrServerReferralSourceMetadataQuery) byField(EmrServerReferralSourceMetadata__c.ReferralSourceInternalId__c, 'IN', externalIds);
	}
}