src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/ApiSchemaSpec__c.field-meta.xml
<CustomField>
    <fullName>ApiSchemaSpec__c</fullName>
    <description>Specifies the API Schema Specifications. Will map to a target class. Eg. if spec is Artemis then a class ArtemisRestClient must exist</description>
    <label>API Schema Spec</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Artemis</fullName>
                <default>true</default>
                <label>Artemis</label>
            </value>
            <value>
                <fullName>Sivis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/InboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>InboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for inbound requests in days. This setting determines how long inbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of inbound requests.</description>
    <inlineHelpText>The number of days to retain logs. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Inbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description>API Name of the Named Credential associated with the EMR Server record, used for authentication purposes.</description>
    <inlineHelpText>Enter the Developer API Name of the Named Credential that will be used for authentication with the EMR Server.</inlineHelpText>
    <label>Named Credential</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/OutboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>OutboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for outbound requests in days. This setting determines how long outbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of outbound requests.</description>
    <inlineHelpText>The number of days to retain requests. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Outbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/TimeoutRequestPeriod__c.field-meta.xml
<CustomField>
    <fullName>TimeoutRequestPeriod__c</fullName>
    <defaultValue>60000</defaultValue>
    <inlineHelpText>In milliseconds</inlineHelpText>
    <label>Timeout request after (ms)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerInboundRequestEvent__e/EmrServerInboundRequestEvent__e.object-meta.xml
<CustomObject>
    <description>Platform Event object used to track and process every single inbound operation coming from external EMR servers.</description>
    <label>EMR Server Inbound Request Event</label>
    <pluralLabel>EMR Server Inbound Request Events</pluralLabel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerInboundRequestEvent__e/fields/EmrServerId__c.field-meta.xml
<CustomField>
    <fullName>EmrServerId__c</fullName>
    <label>EMR Server Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerInboundRequestEvent__e/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerInboundRequestEvent__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerInboundRequestEvent__e/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerInboundRequestEvent__e/fields/StatusMessage__c.field-meta.xml
<CustomField>
    <fullName>StatusMessage__c</fullName>
    <label>Status Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerOutboundRequestEvent__e/EmrServerOutboundRequestEvent__e.object-meta.xml
<CustomObject>
    <description>Platform Event object used to track and log each single outbound EMR REST API operations.</description>
    <label>EMR Server Outbound Request Event</label>
    <pluralLabel>EMR Server Outbound Request Events</pluralLabel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerOutboundRequestEvent__e/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerOutboundRequestEvent__e/fields/RequestDuration__c.field-meta.xml
<CustomField>
    <fullName>RequestDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Request Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerOutboundRequestEvent__e/fields/RequestPayload__c.field-meta.xml
<CustomField>
    <fullName>RequestPayload__c</fullName>
    <label>Request Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerOutboundRequestEvent__e/fields/ResponsePayload__c.field-meta.xml
<CustomField>
    <fullName>ResponsePayload__c</fullName>
    <label>Response Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerOutboundRequestEvent__e/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>Status Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/classes/EmrServer.cls
/**
 * @description  : This class is responsible for managing EMR server configurations and logging operations. Serves as a wrapper for the ErmServer__c settings record.
 * @author       : Ivo Rocha
 * @testSuites   : EMRServerMgmt
 **/
public class EmrServer {
	private static final Integer DEFAULT_TIMEOUT = 60000; // Default timeout of 60 seconds
	private static final Integer MAX_TIMEOUT = 120000; // Maximum timeout of 120 seconds

	public Id emrServerId { get; private set; }
	public String name { get; private set; }
	public String namedCredential { get; private set; }
	public String apiSchemaSpec { get; private set; }
	public Integer inboundRequestsRetentionPeriod { get; private set; }
	public Integer outboundRequestsRetentionPeriod { get; private set; }
	public Integer timeoutRequestsAfter { get; private set; } // in milliseconds
	public EmrServer__c emrServerRecord { get; private set; }

	@TestVisible
	private static final Map<String, EmrServer__c> EMR_SERVERS_MAP = new Map<String, EmrServer__c>();
	static {
		// Initialize the EMR_SERVERS_MAP with all EmrServer__c records
		for (EmrServer__c emrServer : (List<EmrServer__c>) new EmrServerQuery().getList()) {
			EMR_SERVERS_MAP.put(emrServer.Id, emrServer);
			EMR_SERVERS_MAP.put(emrServer.Name, emrServer);
		}
	}

	/**
	 * @description: Private constructor for EmrServer class. To instantiate a new EmrServer object, use the static method getInstance.
	 * @param emrServer: The EmrServer__c record used to initialize the EmrServer instance.
	 */
	private EmrServer(EmrServer__c emrServer) {
		this.emrServerRecord = emrServer;
		this.emrServerId = emrServer.Id;
		this.namedCredential = emrServer.NamedCredential__c;
		this.name = emrServer.Name;
		this.inboundRequestsRetentionPeriod = Math.max(0, Integer.valueOf(emrServer.InboundRequestsRetentionPeriod__c));
		this.outboundRequestsRetentionPeriod = Math.max(0, Integer.valueOf(emrServer.OutboundRequestsRetentionPeriod__c));
		this.timeoutRequestsAfter = Math.min(
			emrServer.TimeoutRequestPeriod__c != null ? Integer.valueOf(emrServer.TimeoutRequestPeriod__c) : DEFAULT_TIMEOUT,
			MAX_TIMEOUT
		);
		this.apiSchemaSpec = emrServer.APISchemaSpec__c;
	}

	/**
	 * @description: Retrieves an instance of EmrServer based on the provided Id.
	 * @param emrServerIdOrName: The Id or Name of the EmrServer__c record.
	 * @return: An instance of EmrServer or null if the record is not found.
	 */
	public static EmrServer getInstance(String emrServerIdOrName) {
		EmrServer__c emrServerRecord = EMR_SERVERS_MAP.get(emrServerIdOrName);
		return emrServerRecord == null ? null : new EmrServer(emrServerRecord);
	}

	/**
	 * @description: Tracks an outbound operation to the EMR server. This method is used to log the details of an outbound operation, including the request and response objects.
	 * @param request: The HttpRequest object representing the outbound operation.
	 * @param response: The HttpResponse object representing the response received from the outbound operation.
	 * @param duration: The duration of the outbound operation in milliseconds.
	 */
	public void trackOutboundRequest(HttpRequest request, HttpResponse response, Long duration) {
		Logger.info('Tracking EMR outbound operation ' + this.emrServerId);

		EmrServerOutboundRequestEvent__e requestEvent = new EmrServerOutboundRequestEvent__e(
			EmrServerId__c = this.emrServerId,
			Endpoint__c = request.getEndpoint()?.left(Schema.EmrServerOutboundRequestEvent__e.fields.Endpoint__c.getDescribe().getLength()),
			Method__c = request.getMethod()?.left(Schema.EmrServerOutboundRequestEvent__e.fields.Method__c.getDescribe().getLength()),
			RequestPayload__c = request.getBody()?.left(Schema.EmrServerOutboundRequestEvent__e.fields.RequestPayload__c.getDescribe().getLength()),
			ResponsePayload__c = response?.getBody()?.left(Schema.EmrServerOutboundRequestEvent__e.fields.ResponsePayload__c.getDescribe().getLength()),
			StatusCode__c = String.valueOf(response?.getStatusCode()),
			StatusMessage__c = response?.getStatus()?.left(Schema.EmrServerOutboundRequestEvent__e.fields.StatusMessage__c.getDescribe().getLength()),
			RequestDuration__c = duration
		);

		publishEvent(requestEvent);

		Logger.saveLog();
	}

	/**
	 * @description: Tracks an outbound operation to the EMR server. This method is used to log the details of an outbound operation whenever the response is not available.
	 * @param request: The HttpRequest object representing the outbound operation.
	 * @param statusCode: The status code of the response received from the outbound operation.
	 * @param statusMessage: The status message of the response received from the outbound operation.
	 */
	public void trackOutboundRequest(HttpRequest request, String statusCode, String statusMessage) {
		Logger.info('Tracking EMR outbound operation ' + this.emrServerId);

		EmrServerOutboundRequestEvent__e requestEvent = new EmrServerOutboundRequestEvent__e(
			EmrServerId__c = this.emrServerId,
			Endpoint__c = request.getEndpoint()?.left(Schema.EmrServerOutboundRequestEvent__e.fields.Endpoint__c.getDescribe().getLength()),
			Method__c = request.getMethod()?.left(Schema.EmrServerOutboundRequestEvent__e.fields.Method__c.getDescribe().getLength()),
			RequestPayload__c = request.getBody()?.left(Schema.EmrServerOutboundRequestEvent__e.fields.RequestPayload__c.getDescribe().getLength()),
			StatusCode__c = statusCode,
			StatusMessage__c = statusMessage
		);

		publishEvent(requestEvent);

		Logger.saveLog();
	}

	/**
	 * @description: Tracks an inbound operation to the EMR server. This method is used to log the details of an inbound operation, including the event, identifier, and resource.
	 * @param event: The event of the inbound operation.
	 * @param identifier: The identifier of the inbound operation.
	 * @param resource: The resource of the inbound operation.
	 * @param payload: The payload of the inbound operation.
	 * @param status: The status of the inbound operation.
	 * @param statusMessage: The status message of the inbound operation.
	 */
	public void reportInboundRequest(String event, String identifier, String resource, String payload, String status, String statusMessage) {
		Logger.info('Tracking EMR inbound operation ' + this.emrServerId);

		EmrServerInboundRequestEvent__e requestEvent = new EmrServerInboundRequestEvent__e(
			EmrServerId__c = this.emrServerId,
			Event__c = event?.toLowerCase(),
			Identifier__c = identifier,
			Resource__c = resource?.toLowerCase(),
			Payload__c = payload,
			Status__c = status?.left(Schema.EmrServerInboundRequestEvent__e.fields.Status__c.getDescribe().getLength()),
			StatusMessage__c = statusMessage?.left(Schema.EmrServerInboundRequestEvent__e.fields.StatusMessage__c.getDescribe().getLength())
		);

		publishEvent(requestEvent);

		Logger.saveLog();
	}

	/**
	 * @description: Publishes a platform event.
	 * @param event: The event to be published.
	 */
	private void publishEvent(SObject event) {
		String eventSObjectName = event.getSObjectType().getDescribe().getName();
		try {
			EventBus.publish(event);
			Logger.info('Published platform event ' + eventSObjectName + ' successfully');
		} catch (Exception ex) {
			Logger.error('Error publishing platform event ' + eventSObjectName, ex);
		}
	}
}