src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/EmrServerContactReference__c.object-meta.xml
<CustomObject>
    <label>EMR Server Contact Reference</label>
    <nameField>
        <displayFormat>ESCR-{0000}</displayFormat>
        <label>EMR Server Contact Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Contact References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>EmrServerContactRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipName>EmrServerContactRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Identifier</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/classes/query-selectors/EmrServerContactReferenceQuery.cls
/**
 * @description  : Query object for EmrServerContactReference__c records.
 * @author       : Ivo Rocha
 **/
public with sharing class EmrServerContactReferenceQuery extends QueryObject {
	public EmrServerContactReferenceQuery() {
		super(EmrServerContactReference__c.SObjectType);
		withAllFields();
		withFields('EmrServer__r.Name');
	}

	public EmrServerContactReferenceQuery byContactId(Contact contact) {
		return byContactId(new Set<Id>{ contact.Id });
	}

	public EmrServerContactReferenceQuery byContactId(List<Contact> contacts) {
		Map<Id, Contact> contactMap = new Map<Id, Contact>(contacts);
		return byContactId(contactMap.keySet());
	}

	public EmrServerContactReferenceQuery byContactId(Id contactId) {
		return byContactId(new Set<Id>{ contactId });
	}

	public EmrServerContactReferenceQuery byContactId(Set<Id> contactIds) {
		return (EmrServerContactReferenceQuery) byField(EmrServerContactReference__c.Contact__c, 'IN', contactIds);
	}

	public EmrServerContactReferenceQuery byEmrServerId(Id emrServerId) {
		return byEmrServerId(new Set<Id>{ emrServerId });
	}

	public EmrServerContactReferenceQuery byEmrServerId(Set<Id> emrServerIds) {
		return (EmrServerContactReferenceQuery) byField(EmrServerContactReference__c.EmrServer__c, 'IN', emrServerIds);
	}

	public EmrServerContactReferenceQuery byIdentifier(String identifier) {
		return byIdentifier(new Set<String>{ identifier });
	}

	public EmrServerContactReferenceQuery byIdentifier(Set<String> identifiers) {
		return (EmrServerContactReferenceQuery) byField(EmrServerContactReference__c.Identifier__c, 'IN', identifiers);
	}
}