src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/ApiSchemaSpec__c.field-meta.xml
<CustomField>
    <fullName>ApiSchemaSpec__c</fullName>
    <description>Specifies the API Schema Specifications. Will map to a target class. Eg. if spec is Artemis then a class ArtemisRestClient must exist</description>
    <label>API Schema Spec</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Artemis</fullName>
                <default>true</default>
                <label>Artemis</label>
            </value>
            <value>
                <fullName>Sivis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/InboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>InboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for inbound requests in days. This setting determines how long inbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of inbound requests.</description>
    <inlineHelpText>The number of days to retain logs. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Inbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description>API Name of the Named Credential associated with the EMR Server record, used for authentication purposes.</description>
    <inlineHelpText>Enter the Developer API Name of the Named Credential that will be used for authentication with the EMR Server.</inlineHelpText>
    <label>Named Credential</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/OutboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>OutboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for outbound requests in days. This setting determines how long outbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of outbound requests.</description>
    <inlineHelpText>The number of days to retain requests. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Outbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/TimeoutRequestPeriod__c.field-meta.xml
<CustomField>
    <fullName>TimeoutRequestPeriod__c</fullName>
    <defaultValue>60000</defaultValue>
    <inlineHelpText>In milliseconds</inlineHelpText>
    <label>Timeout request after (ms)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerInboundRequest__c/EmrServerInboundRequest__c.object-meta.xml
<CustomObject>
    <label>EMR Server Inbound Request</label>
    <nameField>
        <displayFormat>EIR-{0000}</displayFormat>
        <label>EMR Server Inbound Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Inbound Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerInboundRequest__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>Inbound Requests</relationshipLabel>
    <relationshipName>EmrServerInboundRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerOutboundRequest__c/EmrServerOutboundRequest__c.object-meta.xml
<CustomObject>
    <label>EMR Server Outbound Request</label>
    <nameField>
        <displayFormat>EOR-{0000}</displayFormat>
        <label>EMR Server Outbound Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Outbound Request</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerOutboundRequest__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>Outbound Requests</relationshipLabel>
    <relationshipName>EmrServerOutboundRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/classes/tests/EmrServerTest.cls
/**
 * @description  : Unit tests for the EmrServer class.
 * @author       : Ivo Rocha
 * @testSuites   : EMRServerMgmt
 **/
@isTest
private class EmrServerTest {
	@TestSetup
	public static void makeData() {
		insert new EmrServer__c(
			Name = 'XPTO EMR',
			ApiSchemaSpec__c = 'XPTO',
			NamedCredential__c = 'https://unit.xpto.test',
			TimeoutRequestPeriod__c = 50000,
			InboundRequestsRetentionPeriod__c = 10,
			OutboundRequestsRetentionPeriod__c = 15
		);
	}

	private static EmrServer__c getTestEmrServerRecord() {
		return [
			SELECT Id, Name, ApiSchemaSpec__c, TimeoutRequestPeriod__c, InboundRequestsRetentionPeriod__c, OutboundRequestsRetentionPeriod__c
			FROM EmrServer__c
			LIMIT 1
		];
	}

	@isTest
	static void testInstantiationWithExistingServerId() {
		EmrServer emrServer = EmrServer.getInstance(getTestEmrServerRecord().Id);

		Assert.isNotNull(emrServer, 'EmrServer instance should not be null');
		Assert.areEqual('XPTO EMR', emrServer.name, 'Name should match');
		Assert.areEqual('XPTO', emrServer.apiSchemaSpec, 'API Schema Spec should match');
		Assert.areEqual('https://unit.xpto.test', emrServer.namedCredential, 'Named Credential should match');
		Assert.areEqual(10, emrServer.inboundRequestsRetentionPeriod, 'Inbound Retention Period should match');
		Assert.areEqual(15, emrServer.outboundRequestsRetentionPeriod, 'Outbound Retention Period should match');
		Assert.areEqual(50000, emrServer.timeoutRequestsAfter, 'Timeout Requests After should match');
	}

	@isTest
	static void testInstantiationWithoutExistingServerId() {
		EmrServer emrServer = EmrServer.getInstance('001000000000000001');
		Assert.isNull(emrServer, 'EmrServer instance should be null');
	}

	@isTest
	static void shouldTrackOutboundOperationRequest() {
		HttpRequest request = new HttpRequest();
		request.setEndpoint('https://unit.xpto.test');
		request.setMethod('POST');

		HttpResponse response = new HttpResponse();
		response.setStatusCode(200);
		response.setBody('{"status":"success"}');

		Test.startTest();
		EmrServer.getInstance(getTestEmrServerRecord().Id).trackOutboundRequest(request, response, 50000);
		Test.stopTest();

		List<EmrServerOutboundRequest__c> requests = [SELECT Id FROM EmrServerOutboundRequest__c];
		Assert.isTrue(requests.size() > 0, 'Request entry should heve been created');
	}

	@isTest
	static void shouldTrackInboundOperationRequest() {
		EmrServer__c emrServerRecord = getTestEmrServerRecord();

		Test.startTest();
		EmrServer.getInstance(emrServerRecord.Id).reportInboundRequest('Update', '0001', 'Account', '{ "message": "ok"}', 'OK', 'ok');
		Test.stopTest();

		List<EmrServerInboundRequest__c> requests = [SELECT Id FROM EmrServerInboundRequest__c];
		Assert.isTrue(requests.size() > 0, 'Request entries should heve been created');
	}
}