src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerInsuranceCompanyMetadata__c/EmrServerInsuranceCompanyMetadata__c.object-meta.xml
<CustomObject>
    <label>EMR Server Insurance Company Metadata</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Server Insurance Companies Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerInsuranceCompanyMetadata__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>EMR Server Insurance Companies Metadata</relationshipLabel>
    <relationshipName>EmrServerInsuranceCompaniesMetadata</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerInsuranceCompanyMetadata__c/fields/InsuranceCompanyInternalId__c.field-meta.xml
<CustomField>
    <fullName>InsuranceCompanyInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Insurance Company Internal Id</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/code/query-selectors/classes/EmrServerInsuranceCompanyMetadataQuery.cls
/**
 * @description  : This class is used to query the EmrServerInsuranceCompanyMetadata__c object.
 * @author       : Ivo Rocha
 **/
public inherited sharing class EmrServerInsuranceCompanyMetadataQuery extends QueryObject {
	public EmrServerInsuranceCompanyMetadataQuery() {
		super(
			new List<SObjectField>{
				EmrServerInsuranceCompanyMetadata__c.Id,
				EmrServerInsuranceCompanyMetadata__c.Name,
				EmrServerInsuranceCompanyMetadata__c.EmrServer__c,
				EmrServerInsuranceCompanyMetadata__c.InsuranceCompanyInternalId__c
			},
			EmrServerInsuranceCompanyMetadata__c.SObjectType
		);
	}

	public EmrServerInsuranceCompanyMetadataQuery byEmrServerId(Id emrServerId) {
		return byEmrServerId(new Set<Id>{ emrServerId });
	}

	public EmrServerInsuranceCompanyMetadataQuery byEmrServerId(Set<Id> emrServerIds) {
		return (EmrServerInsuranceCompanyMetadataQuery) byField(EmrServerInsuranceCompanyMetadata__c.EmrServer__c, 'IN', emrServerIds);
	}

	public EmrServerInsuranceCompanyMetadataQuery byExternalId(String externalId) {
		return byExternalId(new Set<String>{ externalId });
	}

	public EmrServerInsuranceCompanyMetadataQuery byExternalId(Set<String> externalIds) {
		return (EmrServerInsuranceCompanyMetadataQuery) byField(EmrServerInsuranceCompanyMetadata__c.InsuranceCompanyInternalId__c, 'IN', externalIds);
	}
}