src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/EmrServerContactReference__c.object-meta.xml
<CustomObject>
    <label>EMR Server Contact Reference</label>
    <nameField>
        <displayFormat>ESCR-{0000}</displayFormat>
        <label>EMR Server Contact Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Contact References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerContactReference__c/fields/ArtemisPractitionerIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ArtemisPractitionerIdentifier__c</fullName>
    <externalId>true</externalId>
    <label>Ext</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/EmrServerReferralSourceMetadata__c.object-meta.xml
<CustomObject>
    <label>EMR Server Referral Source Metadata</label>
    <nameField>
        <displayFormat>ESRS-{0000}</displayFormat>
        <label>EMR Server Referral Source Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Referral Sources Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferralCategory__c.field-meta.xml
<CustomField>
    <fullName>ReferralCategory__c</fullName>
    <label>Referral Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferredBy__c.field-meta.xml
<CustomField>
    <fullName>ReferredBy__c</fullName>
    <label>Referred By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/ui-components/lwc-artemis-referral-source-picker/classes/LwcArtemisRefSourcesPickerController.cls
/**
 * @description  :
 * @author       : Ivo Rocha
 **/
public without sharing class LwcArtemisRefSourcesPickerController {
	@AuraEnabled(cacheable=true)
	public static List<EmrServerReferralSourceMetadata__c> geMetadataReferralSources(String emrServerId) {
		if (String.isBlank(emrServerId)) {
			throw new AuraHandledException('LwcArtemisRefSourcesPickerController.getReferralSources: EMR Server ID cannot be null or empty.');
		}

		return new EmrServerReferralSourceMetadataQuery()
			.byEmrServerId(emrServerId)
			.byField(EmrServerReferralSourceMetadata__c.ReferralCategory__c, '!=', 'Doctor_OBGYN')
			.byField(EmrServerReferralSourceMetadata__c.ReferralCategory__c, '!=', 'Doctor_Non OBGYN')
			.byField(EmrServerReferralSourceMetadata__c.ReferralCategory__c, '!=', 'Acupuncturist')
			.orderBy(EmrServerReferralSourceMetadata__c.ReferralCategory__c, true, false)
			.orderBy(EmrServerReferralSourceMetadata__c.ReferredBy__c, true, true)
			.getList();
	}

	@AuraEnabled(cacheable=true)
	public static List<Contact> getPractitioners(String emrServerId) {
		if (String.isBlank(emrServerId)) {
			throw new AuraHandledException('LwcArtemisRefSourcesPickerController.getPractitioners: EMR Server ID cannot be null or empty.');
		}

		List<EmrServerContactReference__c> practitionerReferences = new EmrServerContactReferenceQuery()
			.byEmrServerId(emrServerId)
			.byField(EmrServerContactReference__c.ArtemisPractitionerIdentifier__c, '!=', null)
			.getList();

		return new ProviderQuery().withErmServerReference(practitionerReferences).getList();
	}
}