src/orgs/usa/data-model/objects/Account/fields/LocationArtemisExternalId__c.field-meta.xml
<CustomField>
    <fullName>LocationArtemisExternalId__c</fullName>
    <description>Specific for Location Accounts. Id of the Location in Artemis</description>
    <externalId>true</externalId>
    <label>Location Artemis Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/LocationEmrServer__c.field-meta.xml
<CustomField>
    <fullName>LocationEmrServer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Specific for Location Accounts. The EMR Server associated with the location.</description>
    <label>Artemis Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Contact/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <label>Provider</label>
</RecordType>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/EmrServerContactReference__c.object-meta.xml
<CustomObject>
    <label>EMR Server Contact Reference</label>
    <nameField>
        <displayFormat>ESCR-{0000}</displayFormat>
        <label>EMR Server Contact Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Contact References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>EmrServerContactRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipName>EmrServerContactRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Identifier</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/code/modules/artemis-flow-actions/classes/availabilities/FlowAction_ArtemisAvailabilitiesSearch.cls
/**
 * @description  : Allows to search for availabilities in a given Artemis server from Flows
 * @author       : Ivo Rocha
 * @testSuite    :
 * @testClass    :
 **/
public with sharing class FlowAction_ArtemisAvailabilitiesSearch {
	/**
	 * @description  : Search for availabilities in Artemis
	 * @param        : List<FlowAction_ArtemisAvailabilitiesSearchRequest> requests
	 * @return       : List<List<ArtemisAvailabilityRestModel>>
	 */
	@InvocableMethod(
		label='Search for availabilities in Artemis'
		description='Search for availabilities in Artemis'
		category='Artemis REST Client'
		iconName='slds:standard:invocable_action'
	)
	public static List<List<ArtemisAvailabilityRestModel>> searchAvailabilities(List<FlowAction_ArtemisAvailabilitiesSearchRequest> requests) {
		List<List<ArtemisAvailabilityRestModel>> availabilitiesPerRequest = new List<List<ArtemisAvailabilityRestModel>>();

		Set<String> allProviderIds = new Set<String>();
		Set<String> allLocationIds = new Set<String>();
		Set<Id> emrServerIds = new Set<Id>();
		for (FlowAction_ArtemisAvailabilitiesSearchRequest request : requests) {
			emrServerIds.add(request.emrServerId);

			ArtemisRestClient restClient = (ArtemisRestClient) EmrRestClientFactory.getRestClientInstance(request.emrServerId);

			Date fromDate = request.fromDate != null ? request.fromDate : Date.today();
			Date toDate = request.toDate != null ? request.toDate : fromDate.addDays(7);
			List<String> locationIds = request.locationIds != null ? request.locationIds.split(';') : null;
			List<String> providerIds = request.providerIds != null ? request.providerIds.split(';') : null;

			// We need to enhance the response with additional information about the provider and location of the availability.
			// For this, lets collect the provider and location ids from the response so we can later fetch the related records.
			List<ArtemisAvailabilityRestModel> availabilities = restClient.availabilities.searchAvailabilities(
				request.appointmentType,
				fromDate,
				toDate,
				locationIds,
				providerIds
			);
			for (ArtemisAvailabilityRestModel availability : availabilities) {
				allProviderIds.add(availability.providerId);
				allLocationIds.add(availability.locationId);
				availability.internalContext.put('sourceEmrServerId', request.emrServerId);
			}
			availabilitiesPerRequest.add(availabilities);
		}

		Map<String, EmrServerContactReference__c> ermProviderReferencesByServerAndKey = (Map<String, EmrServerContactReference__c>) Collection.of(
				new EmrServerContactReferenceQuery().byEmrServerId(emrServerIds).byIdentifier(allProviderIds).getList()
			)
			.mapByConcatenation(EmrServerContactReference__c.EmrServer__c, EmrServerContactReference__c.Identifier__c);

		Map<Id, Contact> existingProvidersById = (Map<Id, Contact>) new ProviderQuery()
			.withErmServerReference(ermProviderReferencesByServerAndKey.values())
			.getMapById();

		Map<String, Account> existingLocationsByServerAndKey = (Map<String, Account>) Collection.of(
				new LocationQuery().byEmrServerId(emrServerIds).byExternalId(allLocationIds).getList()
			)
			.mapByConcatenation(Account.LocationEmrServer__c, Account.LocationArtemisExternalId__c);

		// Now that we have the provider and location ids, we can enhance the response with the related records information.
		for (List<ArtemisAvailabilityRestModel> availabilities : availabilitiesPerRequest) {
			for (ArtemisAvailabilityRestModel availability : availabilities) {
				EmrServerContactReference__c ermProviderReference = ermProviderReferencesByServerAndKey.get(
					availability.internalContext.get('sourceEmrServerId') + '' + availability.providerId
				);
				availability.internalContext.put('provider', ermProviderReference != null ? existingProvidersById.get(ermProviderReference.Contact__c) : null);
				availability.internalContext.put(
					'location',
					existingLocationsByServerAndKey.get(availability.internalContext.get('sourceEmrServerId') + '' + availability.locationId)
				);
			}
		}

		return availabilitiesPerRequest;
	}

	public class FlowAction_ArtemisAvailabilitiesSearchRequest {
		@InvocableVariable(label='Artemis Server Id' description='Artemis Server Id' required=true)
		public String emrServerId;

		@InvocableVariable(label='Appointment Type' description='Appointment Type' required=true)
		public String appointmentType;

		@InvocableVariable(label='Location Artemis Ids separated by semicolon' description='Location Artemis Ids separated by semicolon' required=false)
		public String locationIds;

		@InvocableVariable(label='Provider Artemis Ids separated by semicolon' description='Provider Artemis Ids separated by semicolon' required=false)
		public String providerIds;

		@InvocableVariable(label='From Date' description='Defaults to today if left empty' required=false)
		public Date fromDate;

		@InvocableVariable(label='To Date' description='Defaults to 7 days from \'From Date\' if left empty' required=false)
		public Date toDate;
	}
}