src/orgs/usa/data-model/objects/Account/fields/LocationArtemisExternalId__c.field-meta.xml
<CustomField>
    <fullName>LocationArtemisExternalId__c</fullName>
    <description>Specific for Location Accounts. Id of the Location in Artemis</description>
    <externalId>true</externalId>
    <label>Location Artemis Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/LocationBrand__c.field-meta.xml
<CustomField>
    <fullName>LocationBrand__c</fullName>
    <description>Specific for Location Accounts. The brand of the location.</description>
    <label>Location Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/LocationEmrServer__c.field-meta.xml
<CustomField>
    <fullName>LocationEmrServer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Specific for Location Accounts. The EMR Server associated with the location.</description>
    <label>Artemis Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/RetiredBusiness__c.field-meta.xml
<CustomField>
    <fullName>RetiredBusiness__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the business is retired.</description>
    <label>Retired Business</label>
    <type>Checkbox</type>
</CustomField>

src/orgs/usa/data-model/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Boston IVF</fullName>
    </customValue>
    <customValue>
        <fullName>RMA</fullName>
    </customValue>
    <customValue>
        <fullName>Conceptions</fullName>
    </customValue>
    <customValue>
        <fullName>Ovatures</fullName>
    </customValue>
    <customValue>
        <fullName>Peak Men&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Pearl IVF</fullName>
    </customValue>
    <description>Defines the lists of brands that are part of IVIRMA Global.</description>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

src/orgs/usa/code/query-selectors/classes/LocationQuery.cls
/**
 * @description  : Query object for Location (Account) records.
 * @author       : Ivo Rocha
 **/
public inherited sharing class LocationQuery extends QueryObject {
	public LocationQuery() {
		super(
			new List<SObjectField>{
				Account.Id,
				Account.ParentId,
				Account.OwnerId,
				Account.RecordTypeId,
				Account.Name,
				Account.LocationEmrServer__c,
				Account.LocationArtemisExternalId__c,
				Account.LocationBrand__c,
				Account.Type,
				Account.RetiredBusiness__c,
				Account.LocationAddress__CountryCode__s,
				Account.LocationAddress__StateCode__s,
				Account.LocationAddress__City__s,
				Account.LocationAddress__Street__s,
				Account.LocationAddress__PostalCode__s,
				Account.Phone,
				Account.Fax
			},
			Account.SObjectType
		);
		byRecordTypeId(RecordTypes.ACCOUNT_LOCATION.Id);
	}

	public LocationQuery byEmrServerId(Id emrServerId) {
		return byEmrServerId(new Set<Id>{ emrServerId });
	}

	public LocationQuery byEmrServerId(Set<Id> emrServerIds) {
		return (LocationQuery) byField(Account.LocationEmrServer__c, 'IN', emrServerIds);
	}

	public LocationQuery byExternalId(String externalId) {
		return byExternalId(new Set<String>{ externalId });
	}

	public LocationQuery byExternalId(Set<String> externalIds) {
		return (LocationQuery) byField(Account.LocationArtemisExternalId__c, 'IN', externalIds);
	}

	public LocationQuery byBrand(String brand) {
		return byBrand(new Set<String>{ brand });
	}

	public LocationQuery byBrand(Set<String> brands) {
		return (LocationQuery) byField(Account.LocationBrand__c, 'IN', brands);
	}
}