src/orgs/usa/data-model/objects/Account/fields/LocationArtemisExternalId__c.field-meta.xml
<CustomField>
    <fullName>LocationArtemisExternalId__c</fullName>
    <description>Specific for Location Accounts. Id of the Location in Artemis</description>
    <externalId>true</externalId>
    <label>Location Artemis Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/LocationBrand__c.field-meta.xml
<CustomField>
    <fullName>LocationBrand__c</fullName>
    <description>Specific for Location Accounts. The brand of the location.</description>
    <label>Location Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/LocationEmrServer__c.field-meta.xml
<CustomField>
    <fullName>LocationEmrServer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Specific for Location Accounts. The EMR Server associated with the location.</description>
    <label>Artemis Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Boston IVF</fullName>
    </customValue>
    <customValue>
        <fullName>RMA</fullName>
    </customValue>
    <customValue>
        <fullName>Conceptions</fullName>
    </customValue>
    <customValue>
        <fullName>Ovatures</fullName>
    </customValue>
    <customValue>
        <fullName>Peak Men&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Pearl IVF</fullName>
    </customValue>
    <description>Defines the lists of brands that are part of IVIRMA Global.</description>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

src/orgs/usa/code/modules/artemis-data-processors/classes/ArtemisLocationsDataProcessor.cls
/**
 * @description  : This class is responsible for processing Locations data from the Artemis EMR system.
 * @author       : Ivo Rocha
 * @testSuite    : ArtemisDataProcessors
 **/
public inherited sharing class ArtemisLocationsDataProcessor extends EmrServerAbstractDataProcessor {
	public ArtemisLocationsDataProcessor() {
		super();
	}

	Object prepare(Map<EmrServer, List<EmrRestClient.RestModel>> payloadsByServer, List<EmrServer> servers, List<EmrRestClient.RestModel> payloads) {
		Set<String> locationIds = Collection.of(payloads).collect(new LocationIdMapper()).getSetString();
		Set<Id> emrServerIds = Collection.of(servers).collect(new EmrServerIdMapper()).getSetId();

		List<Account> existingLocations = new LocationQuery().byEmrServerId(emrServerIds).byExternalId(locationIds).getList();
		Map<String, Account> locationsByServerAndKey = (Map<String, Account>) Collection.of(
				new LocationQuery().byEmrServerId(emrServerIds).byExternalId(locationIds).getList()
			)
			.mapByConcatenation(Account.LocationEmrServer__c, Account.LocationArtemisExternalId__c);

		LocationPreparedData result = new LocationPreparedData();
		result.existingLocationsByServerAndKey = locationsByServerAndKey;
		return result;
	}

	void handle(EmrRestClient.RestModel payload, EmrServerDataProcessRequestContext context) {
		LocationPreparedData preparedData = (LocationPreparedData) context.preparedData;
		ArtemisLocationRestModel locationPayload = (ArtemisLocationRestModel) payload;

		String sourceEmrServerId = context.sourceServer.emrServerId;
		String locationId = locationPayload.id;

		Account existingLocationRecord = preparedData.existingLocationsByServerAndKey.get(sourceEmrServerId + '' + locationId);

		DatabaseService databaseService = new DatabaseService().asSystemWithoutSharing();
		if (existingLocationRecord == null) {
			Account location = locationPayload.toSObject();
			location.LocationArtemisExternalId__c = locationPayload.id;
			location.LocationEmrServer__c = context.sourceServer.emrServerId;
			location.LocationBrand__c = context.sourceServer.emrServerRecord.NewLocationDefaultBrand__c;
			location.ParentId = context.sourceServer.emrServerRecord.NewLocationDefaultParentAccount__c;

			databaseService.insertRecord(location);
		} else {
			Account location = locationPayload.toSObject(existingLocationRecord.Id);

			databaseService.updateRecord(location);
		}
	}

	private class LocationPreparedData {
		public Map<String, Account> existingLocationsByServerAndKey { get; set; }
	}

	private class LocationIdMapper implements Collection.Mapper {
		public Object value(Object item) {
			return ((ArtemisLocationRestModel) item).id;
		}

		public Type valueType() {
			return String.class;
		}
	}
}