src/orgs/usa/data-model/objects/Account/fields/LocationArtemisExternalId__c.field-meta.xml
<CustomField>
    <fullName>LocationArtemisExternalId__c</fullName>
    <description>Specific for Location Accounts. Id of the Location in Artemis</description>
    <externalId>true</externalId>
    <label>Location Artemis Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/LocationEmrServer__c.field-meta.xml
<CustomField>
    <fullName>LocationEmrServer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Specific for Location Accounts. The EMR Server associated with the location.</description>
    <label>Artemis Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Appointment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/Appointment__c/fields/AppointmentDateTime__c.field-meta.xml
<CustomField>
    <fullName>AppointmentDateTime__c</fullName>
    <label>Appointment Date Time</label>
    <type>DateTime</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/AppointmentType__c.field-meta.xml
<CustomField>
    <fullName>AppointmentType__c</fullName>
    <label>Appointment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/EmrAppointmentId__c.field-meta.xml
<CustomField>
    <fullName>EmrAppointmentId__c</fullName>
    <externalId>true</externalId>
    <label>Artemis Appointment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>Artemis Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>EmrServerAppointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Location account record.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IVIRMA Location Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>LocationAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>PatientAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Provider contact record.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>ProviderAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/RawLocationId__c.field-meta.xml
<CustomField>
    <fullName>RawLocationId__c</fullName>
    <description>Raw location Id received on the payload. To be stored separately in case the matching location does not exist in the system (yet?) and later can be correctly assigned upon its creation.</description>
    <label>Raw Location Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/RawPatientId__c.field-meta.xml
<CustomField>
    <fullName>RawPatientId__c</fullName>
    <description>Raw provider Id received on the payload. To be stored separately in case the matching patient does not exist in the system (yet?) and later can be correctly assigned upon its creation.</description>
    <label>Raw Patient Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/RawProviderId__c.field-meta.xml
<CustomField>
    <fullName>RawProviderId__c</fullName>
    <description>Raw provider Id received on the payload. To be stored separately in case the matching provider does not exist in the system (yet?) and later can be correctly assigned upon its creation.</description>
    <label>Raw Provider Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Contact/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <label>Provider</label>
</RecordType>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/ApiSchemaSpec__c.field-meta.xml
<CustomField>
    <fullName>ApiSchemaSpec__c</fullName>
    <description>Specifies the API Schema Specifications. Will map to a target class. Eg. if spec is Artemis then a class ArtemisRestClient must exist</description>
    <label>API Schema Spec</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Artemis</fullName>
                <default>true</default>
                <label>Artemis</label>
            </value>
            <value>
                <fullName>Sivis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/InboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>InboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for inbound requests in days. This setting determines how long inbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of inbound requests.</description>
    <inlineHelpText>The number of days to retain logs. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Inbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description>API Name of the Named Credential associated with the EMR Server record, used for authentication purposes.</description>
    <inlineHelpText>Enter the Developer API Name of the Named Credential that will be used for authentication with the EMR Server.</inlineHelpText>
    <label>Named Credential</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/OutboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>OutboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for outbound requests in days. This setting determines how long outbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of outbound requests.</description>
    <inlineHelpText>The number of days to retain requests. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Outbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/TimeoutRequestPeriod__c.field-meta.xml
<CustomField>
    <fullName>TimeoutRequestPeriod__c</fullName>
    <defaultValue>60000</defaultValue>
    <inlineHelpText>In milliseconds</inlineHelpText>
    <label>Timeout request after (ms)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/EmrServerAccountReference__c.object-meta.xml
<CustomObject>
    <label>EMR Server Account Reference</label>
    <nameField>
        <displayFormat>ESAR-{0000}</displayFormat>
        <label>EMR Server Account Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Account References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>EmrServerAccountRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipName>EmrServerAccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerAccountReference__c/fields/IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/EmrServerContactReference__c.object-meta.xml
<CustomObject>
    <label>EMR Server Contact Reference</label>
    <nameField>
        <displayFormat>ESCR-{0000}</displayFormat>
        <label>EMR Server Contact Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Contact References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>EmrServerContactRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipName>EmrServerContactRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Identifier</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/code/modules/artemis-data-processors/classes/tests/ArtemisAppointmentsDataProcessorTest.cls
/**
 * @description  : Unit tests for ArtemisAppointmentsDataProcessor
 * @author       : Ivo Rocha
 * @testSuite    : ArtemisDataProcessors
 **/
@isTest
private class ArtemisAppointmentsDataProcessorTest {
	@TestSetup
	static void makeData() {
		EmrServer__c emrServer = new EmrServer__c(
			Name = 'XPTO',
			ApiSchemaSpec__c = 'XPTO',
			NamedCredential__c = 'https://unit.xpto.test',
			TimeoutRequestPeriod__c = 50000,
			InboundRequestsRetentionPeriod__c = 10,
			OutboundRequestsRetentionPeriod__c = 15
		);
		insert emrServer;

		Account patient = new Account(RecordTypeId = RecordTypes.ACCOUNT_PATIENT.id, FirstName = 'Foo', LastName = 'Bar');
		insert patient;

		EmrServerAccountReference__c ermPatientReference = new EmrServerAccountReference__c(
			EmrServer__c = emrServer.Id,
			Account__c = patient.Id,
			Identifier__c = '12345',
			IsPrimary__c = true
		);
		insert ermPatientReference;

		Contact provider = new Contact(RecordTypeId = RecordTypes.CONTACT_PROVIDER.id, FirstName = 'Provider Foo', LastName = 'Provider Bar');
		insert provider;

		EmrServerContactReference__c ermProviderReference = new EmrServerContactReference__c(
			EmrServer__c = emrServer.Id,
			Contact__c = provider.Id,
			Identifier__c = '1001'
		);
		insert ermProviderReference;

		Account location = new Account(
			RecordTypeId = RecordTypes.ACCOUNT_LOCATION.id,
			Name = 'Location Foo Bar',
			LocationEmrServer__c = emrServer.Id,
			LocationArtemisExternalId__c = '2002'
		);
		insert location;

		Appointment__c appointment = new Appointment__c(
			EmrServer__c = emrServer.Id,
			EmrAppointmentId__c = '00001',
			Patient__c = patient.Id,
			Provider__c = provider.Id,
			Location__c = location.Id,
			AppointmentType__c = 'New Patient',
			Status__c = 'Scheduled',
			AppointmentDateTime__c = DateTime.now()
		);
		insert appointment;
	}

	@isTest
	static void shouldCreateNewAppointment() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');

		ArtemisAppointmentRestModel payloadModel = new ArtemisAppointmentRestModel();
		payloadModel.id = '12345';
		payloadModel.patientId = '12345';
		payloadModel.providerId = '1001';
		payloadModel.locationId = '2002';
		payloadModel.appointmentType = 'New Patient';
		payloadModel.appointmentStatus = 'Scheduled';
		payloadModel.appointmentDateTime = DateTime.now();

		ArtemisAppointmentsDataProcessor processor = new ArtemisAppointmentsDataProcessor();
		processor.add(emrServer, payloadModel);

		Test.startTest();
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		Assert.isNotNull(results, 'Results should not be null');
		Assert.areEqual(1, results.size(), 'There should be one result');
		Assert.isTrue(results[0].isSuccess(), 'The result should be successful');

		Assert.areEqual(2, new AppointmentQuery().getCount(), 'There should be two appointments in the database');
		Appointment__c appointment = (Appointment__c) new AppointmentQuery()
			.byEmrServerId(emrServer.emrServerId)
			.byExternalId(new Set<String>{ payloadModel.id })
			.getFirstOrNull();

		Assert.areEqual(payloadModel.id, appointment.EmrAppointmentId__c, 'The appointment should have the correct id');
		Assert.isNotNull(appointment.Patient__c, 'The appointment should have a patient');
		Assert.areEqual(payloadModel.patientId, appointment.RawPatientId__c, 'The appointment should have the correct patient id');
		Assert.isNotNull(appointment.Provider__c, 'The appointment should have a provider');
		Assert.areEqual(payloadModel.providerId, appointment.RawProviderId__c, 'The appointment should have the correct provider id');
		Assert.isNotNull(appointment.Location__c, 'The appointment should have a location');
		Assert.areEqual(payloadModel.locationId, appointment.RawLocationId__c, 'The appointment should have the correct location id');
		Assert.areEqual(payloadModel.appointmentType, appointment.AppointmentType__c, 'The appointment should have the correct type');
		Assert.areEqual(payloadModel.appointmentStatus, appointment.Status__c, 'The appointment should have the correct status');
	}

	@isTest
	static void shouldUpdateExistingAppointment() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');

		ArtemisAppointmentRestModel payloadModel = new ArtemisAppointmentRestModel();
		payloadModel.id = '00001';
		payloadModel.patientId = '12345';
		payloadModel.providerId = '1001';
		payloadModel.locationId = '2002';
		payloadModel.appointmentType = 'New Patient';
		payloadModel.appointmentStatus = 'Scheduled';
		payloadModel.appointmentDateTime = DateTime.now();

		ArtemisAppointmentsDataProcessor processor = new ArtemisAppointmentsDataProcessor();
		processor.add(emrServer, payloadModel);

		Test.startTest();
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		Assert.isNotNull(results, 'Results should not be null');
		Assert.areEqual(1, results.size(), 'There should be one result');
		Assert.isTrue(results[0].isSuccess(), 'The result should be successful');

		Assert.areEqual(1, new AppointmentQuery().getCount(), 'There should be there only one appointment in the database');
		Appointment__c appointment = (Appointment__c) new AppointmentQuery()
			.byEmrServerId(emrServer.emrServerId)
			.byExternalId(new Set<String>{ payloadModel.id })
			.getFirstOrNull();

		Assert.areEqual(payloadModel.id, appointment.EmrAppointmentId__c, 'The appointment should have the correct id');
		Assert.isNotNull(appointment.Patient__c, 'The appointment should have a patient');
		Assert.areEqual(payloadModel.patientId, appointment.RawPatientId__c, 'The appointment should have the correct patient id');
		Assert.isNotNull(appointment.Provider__c, 'The appointment should have a provider');
		Assert.areEqual(payloadModel.providerId, appointment.RawProviderId__c, 'The appointment should have the correct provider id');
		Assert.isNotNull(appointment.Location__c, 'The appointment should have a location');
		Assert.areEqual(payloadModel.locationId, appointment.RawLocationId__c, 'The appointment should have the correct location id');
		Assert.areEqual(payloadModel.appointmentType, appointment.AppointmentType__c, 'The appointment should have the correct type');
		Assert.areEqual(payloadModel.appointmentStatus, appointment.Status__c, 'The appointment should have the correct status');
	}
}