src/orgs/usa/data-model/objects/Account/fields/LocationArtemisExternalId__c.field-meta.xml
<CustomField>
    <fullName>LocationArtemisExternalId__c</fullName>
    <description>Specific for Location Accounts. Id of the Location in Artemis</description>
    <externalId>true</externalId>
    <label>Location Artemis Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/LocationEmrServer__c.field-meta.xml
<CustomField>
    <fullName>LocationEmrServer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Specific for Location Accounts. The EMR Server associated with the location.</description>
    <label>Artemis Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Appointment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/Appointment__c/fields/EmrAppointmentId__c.field-meta.xml
<CustomField>
    <fullName>EmrAppointmentId__c</fullName>
    <externalId>true</externalId>
    <label>Artemis Appointment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>Artemis Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>EmrServerAppointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/EmrServerContactReference__c.object-meta.xml
<CustomObject>
    <label>EMR Server Contact Reference</label>
    <nameField>
        <displayFormat>ESCR-{0000}</displayFormat>
        <label>EMR Server Contact Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Contact References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>EmrServerContactRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipName>EmrServerContactRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Identifier</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/PatientServerProfile__c/PatientServerProfile__c.object-meta.xml
<CustomObject>
    <label>Patient Server Profile</label>
    <nameField>
        <displayFormat>PSP-{0000}</displayFormat>
        <label>Patient Server Profile #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Server Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/PatientServerProfile__c/fields/ArtemisPatientId__c.field-meta.xml
<CustomField>
    <fullName>ArtemisPatientId__c</fullName>
    <externalId>true</externalId>
    <label>Artemis Patient Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/PatientServerProfile__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>Patient Server Profiles</relationshipLabel>
    <relationshipName>PatientServerProfiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/data-model/objects/PatientServerProfile__c/fields/PatientAccount__c.field-meta.xml
<CustomField>
    <fullName>PatientAccount__c</fullName>
    <label>Patient Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Server Profiles</relationshipLabel>
    <relationshipName>PatientServerProfiles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/code/modules/artemis-data-processors/classes/ArtemisAppointmentsDataProcessor.cls
/**
 * @description  : This class is responsible for processing Appointments data from the Artemis EMR system.
 * @author       : Ivo Rocha
 * @testSuite    : ArtemisDataProcessors
 **/
public inherited sharing class ArtemisAppointmentsDataProcessor extends EmrServerAbstractDataProcessor {
	public ArtemisAppointmentsDataProcessor() {
		super();
	}

	Object prepare(Map<EmrServer, List<EmrRestClient.RestModel>> payloadsByServer, List<EmrServer> servers, List<EmrRestClient.RestModel> payloads) {
		Set<Id> emrServerIds = Collection.of(servers).collect(new EmrServerIdMapper()).getSetId();

		// Get existing appointments
		Set<String> appointmentIds = Collection.of(payloads).collect(new AppointmentIdMapper()).getSetString();
		Map<String, Appointment__c> existingAppointmentsByServerAndKey = (Map<String, Appointment__c>) Collection.of(
				new AppointmentQuery().byEmrServerId(emrServerIds).byExternalId(appointmentIds).getList()
			)
			.mapByConcatenation(Appointment__c.EmrServer__c, Appointment__c.EmrAppointmentId__c);

		// Get existing locations
		Set<String> locationIds = Collection.of(payloads).collect(new AppointmentLocationIdMapper()).getSetString();
		locationIds.remove(null); // Remove null id values, if any.
		Map<String, Account> existingLocationsByServerAndKey = (Map<String, Account>) Collection.of(
				new LocationQuery().byEmrServerId(emrServerIds).byExternalId(locationIds).getList()
			)
			.mapByConcatenation(Account.LocationEmrServer__c, Account.LocationArtemisExternalId__c);

		// Get existing providers references
		Set<String> providerIds = Collection.of(payloads).collect(new AppointmentProviderIdMapper()).getSetString();
		providerIds.remove(null); // Remove null id values, if any.
		Map<String, EmrServerContactReference__c> ermProviderReferencesByServerAndKey = (Map<String, EmrServerContactReference__c>) Collection.of(
				new EmrServerContactReferenceQuery().byEmrServerId(emrServerIds).byIdentifier(providerIds).getList()
			)
			.mapByConcatenation(EmrServerContactReference__c.EmrServer__c, EmrServerContactReference__c.Identifier__c);

		// Get existing patients references
		Set<String> patientIds = Collection.of(payloads).collect(new AppointmentPatientIdMapper()).getSetString();
		patientIds.remove(null); // Remove null id values, if any.
		Map<String, PatientServerProfile__c> existingPatientServerProfilesByServerAndKey = (Map<String, PatientServerProfile__c>) Collection.of(
				new PatientServerProfileQuery().byEmrServerId(emrServerIds).byExternalId(patientIds).getList()
			)
			.mapByConcatenation(PatientServerProfile__c.EmrServer__c, PatientServerProfile__c.ArtemisPatientId__c);

		AppointmentPreparedData result = new AppointmentPreparedData();
		result.existingAppointmentsByServerAndKey = existingAppointmentsByServerAndKey;
		result.existingLocationsByServerAndKey = existingLocationsByServerAndKey;
		result.ermProviderReferencesByServerAndKey = ermProviderReferencesByServerAndKey;
		result.existingPatientServerProfilesByServerAndKey = existingPatientServerProfilesByServerAndKey;
		return result;
	}

	void handle(EmrRestClient.RestModel payload, EmrServerDataProcessRequestContext context) {
		AppointmentPreparedData preparedData = (AppointmentPreparedData) context.preparedData;
		ArtemisAppointmentRestModel appointmentPayload = (ArtemisAppointmentRestModel) payload;

		String sourceEmrServerId = context.sourceServer.emrServerId;
		String appointmentId = appointmentPayload.id;

		Appointment__c existingAppointmentRecord = preparedData.existingAppointmentsByServerAndKey.get(sourceEmrServerId + '' + appointmentId);

		ArtemisAppointmentRestModel.ToSObjectContextRefs contextRefs = new ArtemisAppointmentRestModel.ToSObjectContextRefs();
		contextRefs.sfLocationId = preparedData.existingLocationsByServerAndKey.get(sourceEmrServerId + '' + appointmentPayload.locationId)?.Id;
		contextRefs.sfPatientId = preparedData.existingPatientServerProfilesByServerAndKey.get(sourceEmrServerId + '' + appointmentPayload.patientId)
			?.PatientAccount__c;
		contextRefs.sfProviderId = preparedData.ermProviderReferencesByServerAndKey.get(sourceEmrServerId + '' + appointmentPayload.providerId)?.Contact__c;

		DatabaseService databaseService = new DatabaseService().asSystemWithoutSharing();
		if (existingAppointmentRecord == null) {
			Appointment__c appointment = appointmentPayload.toSObject(contextRefs);
			appointment.EmrServer__c = sourceEmrServerId;
			databaseService.insertRecord(appointment);
		} else {
			Appointment__c appointment = appointmentPayload.toSObject(existingAppointmentRecord.Id, contextRefs);
			databaseService.updateRecord(appointment);
		}
	}

	private class AppointmentPreparedData {
		public Map<String, Appointment__c> existingAppointmentsByServerAndKey { get; set; }
		public Map<String, Account> existingLocationsByServerAndKey { get; set; }
		public Map<String, EmrServerContactReference__c> ermProviderReferencesByServerAndKey { get; set; }
		public Map<String, PatientServerProfile__c> existingPatientServerProfilesByServerAndKey { get; set; }
	}

	private class AppointmentIdMapper implements Collection.Mapper {
		public Object value(Object item) {
			return ((ArtemisAppointmentRestModel) item).id;
		}

		public Type valueType() {
			return String.class;
		}
	}

	private class AppointmentLocationIdMapper implements Collection.Mapper {
		public Object value(Object item) {
			return ((ArtemisAppointmentRestModel) item).locationId;
		}

		public Type valueType() {
			return String.class;
		}
	}

	private class AppointmentPatientIdMapper implements Collection.Mapper {
		public Object value(Object item) {
			return ((ArtemisAppointmentRestModel) item).patientId;
		}

		public Type valueType() {
			return String.class;
		}
	}

	private class AppointmentProviderIdMapper implements Collection.Mapper {
		public Object value(Object item) {
			return ((ArtemisAppointmentRestModel) item).providerId;
		}

		public Type valueType() {
			return String.class;
		}
	}
}