src/orgs/usa/data-model/objects/Account/fields/LocationArtemisExternalId__c.field-meta.xml
<CustomField>
    <fullName>LocationArtemisExternalId__c</fullName>
    <description>Specific for Location Accounts. Id of the Location in Artemis</description>
    <externalId>true</externalId>
    <label>Location Artemis Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/LocationEmrServer__c.field-meta.xml
<CustomField>
    <fullName>LocationEmrServer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Specific for Location Accounts. The EMR Server associated with the location.</description>
    <label>Artemis Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/ApiSchemaSpec__c.field-meta.xml
<CustomField>
    <fullName>ApiSchemaSpec__c</fullName>
    <description>Specifies the API Schema Specifications. Will map to a target class. Eg. if spec is Artemis then a class ArtemisRestClient must exist</description>
    <label>API Schema Spec</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Artemis</fullName>
                <default>true</default>
                <label>Artemis</label>
            </value>
            <value>
                <fullName>Sivis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/InboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>InboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for inbound requests in days. This setting determines how long inbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of inbound requests.</description>
    <inlineHelpText>The number of days to retain logs. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Inbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description>API Name of the Named Credential associated with the EMR Server record, used for authentication purposes.</description>
    <inlineHelpText>Enter the Developer API Name of the Named Credential that will be used for authentication with the EMR Server.</inlineHelpText>
    <label>Named Credential</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/OutboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>OutboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for outbound requests in days. This setting determines how long outbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of outbound requests.</description>
    <inlineHelpText>The number of days to retain requests. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Outbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/TimeoutRequestPeriod__c.field-meta.xml
<CustomField>
    <fullName>TimeoutRequestPeriod__c</fullName>
    <defaultValue>60000</defaultValue>
    <inlineHelpText>In milliseconds</inlineHelpText>
    <label>Timeout request after (ms)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/orgs/usa/code/modules/artemis-data-processors/classes/tests/ArtemisLocationsDataProcessorTest.cls
/**
 * @description  : Unit tests for ArtemisLocationsDataProcessor
 * @author       : Ivo Rocha
 * @testSuite    : ArtemisDataProcessors
 **/
@isTest
private class ArtemisLocationsDataProcessorTest {
	@TestSetup
	static void makeData() {
		EmrServer__c emrServer = new EmrServer__c(
			Name = 'XPTO',
			ApiSchemaSpec__c = 'XPTO',
			NamedCredential__c = 'https://unit.xpto.test',
			TimeoutRequestPeriod__c = 50000,
			InboundRequestsRetentionPeriod__c = 10,
			OutboundRequestsRetentionPeriod__c = 15
		);
		insert emrServer;

		Account location = new Account(
			RecordTypeId = RecordTypes.ACCOUNT_LOCATION.id,
			Name = 'Location Foo Bar',
			LocationEmrServer__c = emrServer.Id,
			LocationArtemisExternalId__c = '12345'
		);
		insert location;
	}

	@isTest
	static void shouldCreateNewLocation() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');

		ArtemisLocationRestModel payloadModel = new ArtemisLocationRestModel();
		payloadModel.id = '2002';
		payloadModel.name = 'Location Bar Foo';
		payloadModel.description = 'Location Bar Foo Description';
		payloadModel.address = new ArtemisAddressRestModel();
		payloadModel.address.countryCode = 'US';
		payloadModel.address.stateCode = 'CA';
		payloadModel.address.city = 'San Francisco';
		payloadModel.address.street = '123 Main St';
		payloadModel.address.zip = '12345';

		ArtemisLocationsDataProcessor processor = new ArtemisLocationsDataProcessor();
		processor.add(emrServer, payloadModel);

		Test.startTest();
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		Assert.isNotNull(results, 'Results should not be null');
		Assert.areEqual(1, results.size(), 'There should be one result');
		Assert.isTrue(results[0].isSuccess(), 'The result should be successful');

		Assert.areEqual(
			1,
			[SELECT COUNT() FROM Account WHERE LocationEmrServer__c = :emrServer.emrServerId AND LocationArtemisExternalId__c = :payloadModel.id],
			'The location should be created'
		);
		Account location = (Account) new LocationQuery().byEmrServerId(emrServer.emrServerId).byExternalId(payloadModel.id).getFirstOrNull();

		Assert.areEqual(payloadModel.id, location.LocationArtemisExternalId__c, 'The location should have the correct id');
		Assert.areEqual(payloadModel.name, location.Name, 'The location should have the correct name');
		Assert.areEqual(payloadModel.description, location.Description, 'The location should have the correct description');
		Assert.areEqual(payloadModel.address.countryCode, location.LocationAddress__CountryCode__s, 'The location should have the correct country code');
		Assert.areEqual(payloadModel.address.stateCode, location.LocationAddress__StateCode__s, 'The location should have the correct state code');
		Assert.areEqual(payloadModel.address.city, location.LocationAddress__City__s, 'The location should have the correct city');
		Assert.areEqual(payloadModel.address.street, location.LocationAddress__Street__s, 'The location should have the correct street');
		Assert.areEqual(payloadModel.address.zip, location.LocationAddress__PostalCode__s, 'The location should have the correct zip code');
	}

	@isTest
	static void shouldUpdateExistingLocation() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');

		ArtemisLocationRestModel payloadModel = new ArtemisLocationRestModel();
		payloadModel.id = '12345';
		payloadModel.name = 'Location Bar Foo';

		ArtemisLocationsDataProcessor processor = new ArtemisLocationsDataProcessor();
		processor.add(emrServer, payloadModel);

		Test.startTest();
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		Assert.isNotNull(results, 'Results should not be null');
		Assert.areEqual(1, results.size(), 'There should be one result');
		Assert.isTrue(results[0].isSuccess(), 'The result should be successful');

		Assert.areEqual(
			1,
			[SELECT COUNT() FROM Account WHERE RecordTypeId = :RecordTypes.ACCOUNT_LOCATION.id],
			'There should be there only one location in the database'
		);

		Account location = (Account) new LocationQuery().byEmrServerId(emrServer.emrServerId).byExternalId(payloadModel.id).getFirstOrNull();
		Assert.areEqual(payloadModel.id, location.LocationArtemisExternalId__c, 'The location should have the correct id');
		Assert.areEqual(payloadModel.name, location.Name, 'The location should have the correct name');
	}
}