src/orgs/usa/data-model/objects/Account/fields/PatientCarrotPatient__c.field-meta.xml
<CustomField>
    <fullName>PatientCarrotPatient__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Carrot Patient</label>
    <type>Checkbox</type>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/PatientHowDidYouHearAboutUs__c.field-meta.xml
<CustomField>
    <fullName>PatientHowDidYouHearAboutUs__c</fullName>
    <description>Specific for Patient Accounts. Indicates the method by which the patient heard about us.</description>
    <label>How did you hear about us?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Google Search</fullName>
            </value>
            <value>
                <fullName>Friend/Relative</fullName>
            </value>
            <value>
                <fullName>Insurance Carrier</fullName>
            </value>
            <value>
                <fullName>Facebook/Instagram</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Television</fullName>
            </value>
            <value>
                <fullName>Therapist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/PatientRequestedPatientAdvocate__c.field-meta.xml
<CustomField>
    <fullName>PatientRequestedPatientAdvocate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specific for Patient Accounts. Indicates if the patient requested a patient advocate.</description>
    <label>Requested Patient Advocate</label>
    <type>Checkbox</type>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/PatientRollupBiologicalSex__c.field-meta.xml
<CustomField>
    <fullName>PatientRollupBiologicalSex__c</fullName>
    <description>Specific for Patient Accounts. Rollup field that contains all the biological sex values from the related PatientServerProfile__c record to this Patient Account.</description>
    <label>Biological Sex</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/PatientRollupEthnicity__c.field-meta.xml
<CustomField>
    <fullName>PatientRollupEthnicity__c</fullName>
    <description>Specific for Patient Accounts. Rollup field that contains all the ethnicity values from the related PatientServerProfile__c record to this Patient Account.</description>
    <label>Ethnicity</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hispanic</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Non-Hispanic</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>White non-Hispanic</fullName>
            </value>
            <value>
                <fullName>White Hispanic</fullName>
            </value>
            <value>
                <fullName>Black non-Hispanic</fullName>
            </value>
            <value>
                <fullName>Black Hispanic</fullName>
            </value>
            <value>
                <fullName>Asian non-Hispanic</fullName>
            </value>
            <value>
                <fullName>Asian Hispanic</fullName>
            </value>
            <value>
                <fullName>American Indian</fullName>
            </value>
            <value>
                <fullName>Other, please specify</fullName>
            </value>
            <value>
                <fullName>Refused/Choose not to disclose</fullName>
            </value>
            <value>
                <fullName>American Indian/Alaska Native</fullName>
            </value>
            <value>
                <fullName>Asian</fullName>
            </value>
            <value>
                <fullName>Black/African American</fullName>
            </value>
            <value>
                <fullName>Hispanic/Latino</fullName>
            </value>
            <value>
                <fullName>Native Hawaiian/Other Pacific</fullName>
            </value>
            <value>
                <fullName>White/Caucasian</fullName>
            </value>
            <value>
                <fullName>Not Asked</fullName>
            </value>
            <value>
                <fullName>Not Provided</fullName>
            </value>
            <value>
                <fullName>Asked but unknown</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/PatientRollupGenderIdentity__c.field-meta.xml
<CustomField>
    <fullName>PatientRollupGenderIdentity__c</fullName>
    <description>Specific for Patient Accounts. Rollup field that contains all the gender identity values from the related PatientServerProfile__c record to this Patient Account. This field was not defined as a picklist due to the existance of picklist entry values with larger text lengths higher than the maximum allowed for a picklist field.</description>
    <label>Gender Identity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/PatientRollupMaritalStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientRollupMaritalStatus__c</fullName>
    <description>Specific for Patient Accounts. Rollup field that contains all the marital status values from the related PatientServerProfile__c record to this Patient Account.</description>
    <label>Marital Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Divorced</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Widowed</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/PatientRollupRace__c.field-meta.xml
<CustomField>
    <fullName>PatientRollupRace__c</fullName>
    <description>Specific for Patient Accounts. Rollup field that contains all the race values from the related PatientServerProfile__c record to this Patient Account. This field was not defined as a picklist due to the existance of picklist entry values with larger text lengths higher than the maximum allowed for a picklist field.</description>
    <label>Race</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/PatientRollupSexualOrientation__c.field-meta.xml
<CustomField>
    <fullName>PatientRollupSexualOrientation__c</fullName>
    <description>Specific for Patient Accounts. Rollup field that contains all the sexual orientation values from the related PatientServerProfile__c record to this Patient Account.</description>
    <label>Sexual Orientation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Straight or heterosexual</fullName>
            </value>
            <value>
                <fullName>Lesbian, gay or homosexual</fullName>
            </value>
            <value>
                <fullName>Bisexual</fullName>
            </value>
            <value>
                <fullName>Something else</fullName>
            </value>
            <value>
                <fullName>Don&apos;t know</fullName>
            </value>
            <value>
                <fullName>Choose not to disclose</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Other, please specify</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Account/fields/PatientType__c.field-meta.xml
<CustomField>
    <fullName>PatientType__c</fullName>
    <description>Specific for Patient Accounts. Indicates the type of patient.</description>
    <label>Patient Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General Infertility</fullName>
            </value>
            <value>
                <fullName>Fertility Preservation</fullName>
            </value>
            <value>
                <fullName>Registered in WinMed</fullName>
            </value>
            <value>
                <fullName>Donor</fullName>
            </value>
            <value>
                <fullName>GC Recipient</fullName>
            </value>
            <value>
                <fullName>GYN Only</fullName>
            </value>
            <value>
                <fullName>Monitoring Only</fullName>
            </value>
            <value>
                <fullName>Infertility</fullName>
            </value>
            <value>
                <fullName>Valerie Fund Patient</fullName>
            </value>
            <value>
                <fullName>LMN Owned</fullName>
            </value>
            <value>
                <fullName>LER Owned</fullName>
            </value>
            <value>
                <fullName>Former IVFNJ</fullName>
            </value>
            <value>
                <fullName>Nutrition Counsel Only</fullName>
            </value>
            <value>
                <fullName>International Patient</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Cancer Patient</fullName>
            </value>
            <value>
                <fullName>Patient Inquiry</fullName>
            </value>
            <value>
                <fullName>Patient Portal</fullName>
            </value>
            <value>
                <fullName>Referral Patient</fullName>
            </value>
            <value>
                <fullName>Directed Sperm Donor</fullName>
            </value>
            <value>
                <fullName>Intended Parent</fullName>
            </value>
            <value>
                <fullName>GC Recipient Partner</fullName>
            </value>
            <value>
                <fullName>FPE-Physician in Training</fullName>
            </value>
            <value>
                <fullName>Non-Tech Patient</fullName>
            </value>
            <value>
                <fullName>Abandoned Patient</fullName>
            </value>
            <value>
                <fullName>Endocrine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/PatientServerProfile__c/PatientServerProfile__c.object-meta.xml
<CustomObject>
    <label>Patient Server Profile</label>
    <nameField>
        <displayFormat>PSP-{0000}</displayFormat>
        <label>Patient Server Profile #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Server Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/PatientServerProfile__c/fields/PatientType__c.field-meta.xml
<CustomField>
    <fullName>PatientType__c</fullName>
    <label>Patient Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General Infertility</fullName>
            </value>
            <value>
                <fullName>Fertility Preservation</fullName>
            </value>
            <value>
                <fullName>Registered in WinMed</fullName>
            </value>
            <value>
                <fullName>Donor</fullName>
            </value>
            <value>
                <fullName>GC Recipient</fullName>
            </value>
            <value>
                <fullName>GYN Only</fullName>
            </value>
            <value>
                <fullName>Monitoring Only</fullName>
            </value>
            <value>
                <fullName>Infertility</fullName>
            </value>
            <value>
                <fullName>Valerie Fund Patient</fullName>
            </value>
            <value>
                <fullName>LMN Owned</fullName>
            </value>
            <value>
                <fullName>LER Owned</fullName>
            </value>
            <value>
                <fullName>Former IVFNJ</fullName>
            </value>
            <value>
                <fullName>Nutrition Counsel Only</fullName>
            </value>
            <value>
                <fullName>International Patient</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Cancer Patient</fullName>
            </value>
            <value>
                <fullName>Patient Inquiry</fullName>
            </value>
            <value>
                <fullName>Patient Portal</fullName>
            </value>
            <value>
                <fullName>Referral Patient</fullName>
            </value>
            <value>
                <fullName>Directed Sperm Donor</fullName>
            </value>
            <value>
                <fullName>Intended Parent</fullName>
            </value>
            <value>
                <fullName>GC Recipient Partner</fullName>
            </value>
            <value>
                <fullName>FPE-Physician in Training</fullName>
            </value>
            <value>
                <fullName>Non-Tech Patient</fullName>
            </value>
            <value>
                <fullName>Abandoned Patient</fullName>
            </value>
            <value>
                <fullName>Endocrine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/code/query-selectors/classes/PatientQuery.cls
/**
 * @description  : Query object for Patient (Account/PersonAccount) records.
 * @author       : Ivo Rocha
 **/
public inherited sharing class PatientQuery extends QueryObject {
	public PatientQuery() {
		// Note: Account.Name should never be added in the query. Doing any update on a Person Account with the Name in the object instance will throw a DML Exception.
		super(
			new List<SObjectField>{
				Account.Id,
				Account.OwnerId,
				Account.RecordTypeId,
				Account.Salutation,
				Account.PreferredFirstName__pc,
				Account.FirstName,
				Account.MiddleName,
				Account.LastName,
				Account.Suffix,
				Account.Deceased__pc,
				Account.PersonBirthdate,
				Account.Age__pc,
				Account.SocialSecurityNumber__pc,
				Account.EmployerCompanyName__pc,
				Account.PatientCarrotPatient__c,
				Account.PatientType__c,
				Account.PatientHowDidYouHearAboutUs__c,
				Account.PatientRequestedPatientAdvocate__c,
				Account.PatientRollupBiologicalSex__c,
				Account.PatientRollupRace__c,
				Account.PatientRollupEthnicity__c,
				Account.PatientRollupGenderIdentity__c,
				Account.PatientRollupSexualOrientation__c,
				Account.PatientRollupMaritalStatus__c,
				Account.PatientRollupInterests__c,
				Account.PatientRollupLanguage__c,
				Account.PatientRollupPronouns__c
			},
			Account.SObjectType
		);
		byRecordTypeId(RecordTypes.ACCOUNT_PATIENT.Id);
	}

	public PatientQuery withErmServerReference(EmrServerAccountReference__c ermReference) {
		return withErmServerReference(new List<EmrServerAccountReference__c>{ ermReference });
	}

	public PatientQuery withErmServerReference(List<EmrServerAccountReference__c> ermReferences) {
		return (PatientQuery) relatedToChildren(ermReferences, EmrServerAccountReference__c.Account__c);
	}

	public PatientQuery bySocialSecurityNumber(String socialSecurityNumber) {
		return bySocialSecurityNumber(new Set<String>{ socialSecurityNumber });
	}

	public PatientQuery bySocialSecurityNumber(Set<String> socialSecurityNumbers) {
		return (PatientQuery) byField(Account.SocialSecurityNumber__pc, 'IN', socialSecurityNumbers);
	}

	public PatientQuery withPatientServerProfiles() {
		return (PatientQuery) withChildren(new PatientServerProfileQuery(), 'PatientServerProfiles__r');
	}
}