src/orgs/usa/data-model/objects/Contact/fields/AdditionalEmail__c.field-meta.xml
<CustomField>
    <fullName>AdditionalEmail__c</fullName>
    <label>Additional Email</label>
    <type>Email</type>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderNpi__c.field-meta.xml
<CustomField>
    <fullName>ProviderNpi__c</fullName>
    <label>NPI #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderSpecialty__c.field-meta.xml
<CustomField>
    <fullName>ProviderSpecialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allergy/immunology</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Cardiovascular Disease</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Endocrinology</fullName>
            </value>
            <value>
                <fullName>Family Practice</fullName>
            </value>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>General Practice</fullName>
            </value>
            <value>
                <fullName>Genetic Counselor</fullName>
            </value>
            <value>
                <fullName>Gynecology/oncology</fullName>
            </value>
            <value>
                <fullName>Hematology/oncology</fullName>
            </value>
            <value>
                <fullName>Infectious Disease</fullName>
            </value>
            <value>
                <fullName>Internal Medicine, General</fullName>
            </value>
            <value>
                <fullName>Maternal And Fetal Medicine</fullName>
            </value>
            <value>
                <fullName>Medical Oncology</fullName>
            </value>
            <value>
                <fullName>Midwife</fullName>
            </value>
            <value>
                <fullName>Nephrology</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Nuclear Medicine</fullName>
            </value>
            <value>
                <fullName>Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>Obstetrics/gynecology</fullName>
            </value>
            <value>
                <fullName>Ophthalmology</fullName>
            </value>
            <value>
                <fullName>Orthopedic Surgery</fullName>
            </value>
            <value>
                <fullName>Pediatrics</fullName>
            </value>
            <value>
                <fullName>Physician&apos;s Assistant</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Pulmonary Disease</fullName>
            </value>
            <value>
                <fullName>Radiation Oncology</fullName>
            </value>
            <value>
                <fullName>Radiology</fullName>
            </value>
            <value>
                <fullName>Reproductive Endocrinologist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/code/modules/artemis-rest-client/classes/models/ArtemisPractitionerRestModel.cls
/**
 * @description  : This class represents a practitioner in the Artemis Rest API.
 * @author       : Ivo Rocha
 **/
public class ArtemisPractitionerRestModel extends EmrRestClient.RestModel {
	public String id;
	public String firstName;
	public String lastName;
	public String middleName;
	public String suffix;
	public String title;
	public String npi;
	public String email;
	public String additionalEmail;
	//public List<String> languages;
	//public List<String> medicalDegrees;
	public String specialty;
	public ArtemisAddressRestModel address;
	public String phone;

	public Contact toSObject() {
		return toSObject(null);
	}

	public Contact toSObject(Id recordId) {
		Contact contact = new Contact(Id = recordId);
		contact.RecordTypeId = RecordTypes.CONTACT_PROVIDER.Id;
		contact.FirstName = firstName;
		contact.MiddleName = middleName;
		contact.LastName = lastName;
		contact.Suffix = suffix;
		contact.Title = title;
		contact.ProviderNpi__c = npi;
		contact.Email = email;
		contact.AdditionalEmail__c = additionalEmail;
		contact.Phone = phone;
		contact.ProviderSpecialty__c = specialty;

		if (this.address != null) {
			contact.MailingCountryCode = this.address.countryCode;
			contact.MailingStateCode = this.address.stateCode;
			contact.MailingCity = this.address.city;
			contact.MailingStreet = this.address.street;
			contact.MailingPostalCode = this.address.zip;
		}

		return contact;
	}
}