src/orgs/usa/data-model/objects/Contact/fields/AdditionalEmail__c.field-meta.xml
<CustomField>
    <fullName>AdditionalEmail__c</fullName>
    <label>Additional Email</label>
    <type>Email</type>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderMedicalDegree__c.field-meta.xml
<CustomField>
    <fullName>ProviderMedicalDegree__c</fullName>
    <label>Medical Degree</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANP</fullName>
            </value>
            <value>
                <fullName>APRN</fullName>
            </value>
            <value>
                <fullName>ARNP</fullName>
            </value>
            <value>
                <fullName>CGC</fullName>
            </value>
            <value>
                <fullName>CNM</fullName>
            </value>
            <value>
                <fullName>CNP</fullName>
            </value>
            <value>
                <fullName>DNP</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>FNP</fullName>
            </value>
            <value>
                <fullName>FNP-C</fullName>
            </value>
            <value>
                <fullName>LICSW</fullName>
            </value>
            <value>
                <fullName>LPN</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NP</fullName>
            </value>
            <value>
                <fullName>NP-C</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PA-C</fullName>
            </value>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>RDMS</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RPA-C</fullName>
            </value>
            <value>
                <fullName>WHNP</fullName>
            </value>
            <value>
                <fullName>WHNP-BC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderNpi__c.field-meta.xml
<CustomField>
    <fullName>ProviderNpi__c</fullName>
    <label>NPI #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderSpecialty__c.field-meta.xml
<CustomField>
    <fullName>ProviderSpecialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allergy/immunology</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Cardiovascular Disease</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Endocrinology</fullName>
            </value>
            <value>
                <fullName>Family Practice</fullName>
            </value>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>General Practice</fullName>
            </value>
            <value>
                <fullName>Genetic Counselor</fullName>
            </value>
            <value>
                <fullName>Gynecology/oncology</fullName>
            </value>
            <value>
                <fullName>Hematology/oncology</fullName>
            </value>
            <value>
                <fullName>Infectious Disease</fullName>
            </value>
            <value>
                <fullName>Internal Medicine, General</fullName>
            </value>
            <value>
                <fullName>Maternal And Fetal Medicine</fullName>
            </value>
            <value>
                <fullName>Medical Oncology</fullName>
            </value>
            <value>
                <fullName>Midwife</fullName>
            </value>
            <value>
                <fullName>Nephrology</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Nuclear Medicine</fullName>
            </value>
            <value>
                <fullName>Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>Obstetrics/gynecology</fullName>
            </value>
            <value>
                <fullName>Ophthalmology</fullName>
            </value>
            <value>
                <fullName>Orthopedic Surgery</fullName>
            </value>
            <value>
                <fullName>Pediatrics</fullName>
            </value>
            <value>
                <fullName>Physician&apos;s Assistant</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Pulmonary Disease</fullName>
            </value>
            <value>
                <fullName>Radiation Oncology</fullName>
            </value>
            <value>
                <fullName>Radiology</fullName>
            </value>
            <value>
                <fullName>Reproductive Endocrinologist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderStaffLanguage__c.field-meta.xml
<CustomField>
    <fullName>ProviderStaffLanguage__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Greek</fullName>
            </value>
            <value>
                <fullName>Gujarati</fullName>
            </value>
            <value>
                <fullName>Hebrew</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Hmong</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Persian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Punjabi</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Tagalog</fullName>
            </value>
            <value>
                <fullName>Telugu</fullName>
            </value>
            <value>
                <fullName>Urdu</fullName>
            </value>
            <value>
                <fullName>Vietnamese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Contact/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <label>Provider</label>
</RecordType>

src/orgs/usa/code/modules/artemis-rest-client/classes/models/ArtemisProviderRestModel.cls
/**
 * @description  : This class represents a provider in the Artemis Rest API.
 * @author       : Ivo Rocha
 **/
public class ArtemisProviderRestModel extends EmrRestClient.RestModel {
	public String id;
	public String firstName;
	public String lastName;
	public String middleName;
	public String suffix;
	public String title;
	public String npi;
	public String email;
	public String additionalEmail;
	public List<String> languages;
	public List<String> medicalDegrees;
	public String specialty;
	public ArtemisAddressRestModel address;
	public String phone;
	public String calendarId;

	public Contact toSObject() {
		return toSObject(null);
	}

	public Contact toSObject(Id recordId) {
		Contact contact = new Contact(Id = recordId);
		contact.RecordTypeId = RecordTypes.CONTACT_PROVIDER.Id;
		contact.FirstName = this.firstName;
		contact.MiddleName = this.middleName;
		contact.LastName = this.lastName;
		contact.Suffix = this.suffix;
		contact.Title = this.title;
		contact.ProviderNpi__c = this.npi;
		contact.Email = this.email;
		contact.AdditionalEmail__c = this.additionalEmail;
		contact.ProviderStaffLanguage__c = this.languages != null ? String.join(this.languages, ';') : null;
		contact.ProviderMedicalDegree__c = this.medicalDegrees != null ? String.join(this.medicalDegrees, ';') : null;
		contact.ProviderSpecialty__c = this.specialty;
		contact.Phone = this.phone;

		if (this.address != null) {
			contact.MailingCountryCode = this.address.countryCode;
			contact.MailingStateCode = this.address.stateCode;
			contact.MailingCity = this.address.city;
			contact.MailingStreet = this.address.street;
			contact.MailingPostalCode = this.address.zip;
		}

		return contact;
	}
}