src/orgs/usa/data-model/objects/Contact/fields/AdditionalEmail__c.field-meta.xml
<CustomField>
    <fullName>AdditionalEmail__c</fullName>
    <label>Additional Email</label>
    <type>Email</type>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderMedicalDegree__c.field-meta.xml
<CustomField>
    <fullName>ProviderMedicalDegree__c</fullName>
    <label>Medical Degree</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANP</fullName>
            </value>
            <value>
                <fullName>APRN</fullName>
            </value>
            <value>
                <fullName>ARNP</fullName>
            </value>
            <value>
                <fullName>CGC</fullName>
            </value>
            <value>
                <fullName>CNM</fullName>
            </value>
            <value>
                <fullName>CNP</fullName>
            </value>
            <value>
                <fullName>DNP</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>FNP</fullName>
            </value>
            <value>
                <fullName>FNP-C</fullName>
            </value>
            <value>
                <fullName>LICSW</fullName>
            </value>
            <value>
                <fullName>LPN</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NP</fullName>
            </value>
            <value>
                <fullName>NP-C</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PA-C</fullName>
            </value>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>RDMS</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RPA-C</fullName>
            </value>
            <value>
                <fullName>WHNP</fullName>
            </value>
            <value>
                <fullName>WHNP-BC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderNpi__c.field-meta.xml
<CustomField>
    <fullName>ProviderNpi__c</fullName>
    <label>NPI #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderSpecialty__c.field-meta.xml
<CustomField>
    <fullName>ProviderSpecialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allergy/immunology</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Cardiovascular Disease</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Endocrinology</fullName>
            </value>
            <value>
                <fullName>Family Practice</fullName>
            </value>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>General Practice</fullName>
            </value>
            <value>
                <fullName>Genetic Counselor</fullName>
            </value>
            <value>
                <fullName>Gynecology/oncology</fullName>
            </value>
            <value>
                <fullName>Hematology/oncology</fullName>
            </value>
            <value>
                <fullName>Infectious Disease</fullName>
            </value>
            <value>
                <fullName>Internal Medicine, General</fullName>
            </value>
            <value>
                <fullName>Maternal And Fetal Medicine</fullName>
            </value>
            <value>
                <fullName>Medical Oncology</fullName>
            </value>
            <value>
                <fullName>Midwife</fullName>
            </value>
            <value>
                <fullName>Nephrology</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Nuclear Medicine</fullName>
            </value>
            <value>
                <fullName>Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>Obstetrics/gynecology</fullName>
            </value>
            <value>
                <fullName>Ophthalmology</fullName>
            </value>
            <value>
                <fullName>Orthopedic Surgery</fullName>
            </value>
            <value>
                <fullName>Pediatrics</fullName>
            </value>
            <value>
                <fullName>Physician&apos;s Assistant</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Pulmonary Disease</fullName>
            </value>
            <value>
                <fullName>Radiation Oncology</fullName>
            </value>
            <value>
                <fullName>Radiology</fullName>
            </value>
            <value>
                <fullName>Reproductive Endocrinologist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderStaffLanguage__c.field-meta.xml
<CustomField>
    <fullName>ProviderStaffLanguage__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Greek</fullName>
            </value>
            <value>
                <fullName>Gujarati</fullName>
            </value>
            <value>
                <fullName>Hebrew</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Hmong</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Persian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Punjabi</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Tagalog</fullName>
            </value>
            <value>
                <fullName>Telugu</fullName>
            </value>
            <value>
                <fullName>Urdu</fullName>
            </value>
            <value>
                <fullName>Vietnamese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Contact/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <label>Provider</label>
</RecordType>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/EmrServerContactReference__c.object-meta.xml
<CustomObject>
    <label>EMR Server Contact Reference</label>
    <nameField>
        <displayFormat>ESCR-{0000}</displayFormat>
        <label>EMR Server Contact Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Contact References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>EmrServerContactRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/code/query-selectors/classes/ProviderQuery.cls
/**
 * @description  : Query object for Provider (Contact) records.
 * @author       : Ivo Rocha
 **/
public inherited sharing class ProviderQuery extends QueryObject {
	public ProviderQuery() {
		super(
			new List<SObjectField>{
				Contact.Id,
				Contact.OwnerId,
				Contact.RecordTypeId,
				Contact.AccountId,
				Contact.Title,
				Contact.Salutation,
				Contact.Name,
				Contact.FirstName,
				Contact.MiddleName,
				Contact.LastName,
				Contact.Suffix,
				Contact.ProviderMedicalDegree__c,
				Contact.ProviderSpecialty__c,
				Contact.ProviderStaffLanguage__c,
				Contact.MailingCountryCode,
				Contact.MailingStateCode,
				Contact.MailingCity,
				Contact.MailingStreet,
				Contact.MailingPostalCode,
				Contact.Phone,
				Contact.MobilePhone,
				Contact.Fax,
				Contact.Email,
				Contact.AdditionalEmail__c,
				Contact.ProviderNpi__c
			},
			Contact.SObjectType
		);
		byRecordTypeId(RecordTypes.CONTACT_PROVIDER.Id);
	}

	public ProviderQuery withErmServerReference(EmrServerContactReference__c ermReference) {
		return withErmServerReference(new List<EmrServerContactReference__c>{ ermReference });
	}

	public ProviderQuery withErmServerReference(List<EmrServerContactReference__c> ermReferences) {
		return (ProviderQuery) relatedToChildren(ermReferences, EmrServerContactReference__c.Contact__c);
	}

	public ProviderQuery byNpi(String npi) {
		return byNpi(new Set<String>{ npi });
	}

	public ProviderQuery byNpi(Set<String> npis) {
		return (ProviderQuery) byField(Contact.ProviderNpi__c, 'IN', npis);
	}

	public ProviderQuery byNonEmptyNpi() {
		return (ProviderQuery) byField(Contact.ProviderNpi__c, '!=', null);
	}
}