src/orgs/usa/data-model/objects/Contact/fields/AdditionalEmail__c.field-meta.xml
<CustomField>
    <fullName>AdditionalEmail__c</fullName>
    <label>Additional Email</label>
    <type>Email</type>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderMedicalDegree__c.field-meta.xml
<CustomField>
    <fullName>ProviderMedicalDegree__c</fullName>
    <label>Medical Degree</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANP</fullName>
            </value>
            <value>
                <fullName>APRN</fullName>
            </value>
            <value>
                <fullName>ARNP</fullName>
            </value>
            <value>
                <fullName>CGC</fullName>
            </value>
            <value>
                <fullName>CNM</fullName>
            </value>
            <value>
                <fullName>CNP</fullName>
            </value>
            <value>
                <fullName>DNP</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>FNP</fullName>
            </value>
            <value>
                <fullName>FNP-C</fullName>
            </value>
            <value>
                <fullName>LICSW</fullName>
            </value>
            <value>
                <fullName>LPN</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NP</fullName>
            </value>
            <value>
                <fullName>NP-C</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PA-C</fullName>
            </value>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>RDMS</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RPA-C</fullName>
            </value>
            <value>
                <fullName>WHNP</fullName>
            </value>
            <value>
                <fullName>WHNP-BC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderSpecialty__c.field-meta.xml
<CustomField>
    <fullName>ProviderSpecialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allergy/immunology</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Cardiovascular Disease</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Endocrinology</fullName>
            </value>
            <value>
                <fullName>Family Practice</fullName>
            </value>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>General Practice</fullName>
            </value>
            <value>
                <fullName>Genetic Counselor</fullName>
            </value>
            <value>
                <fullName>Gynecology/oncology</fullName>
            </value>
            <value>
                <fullName>Hematology/oncology</fullName>
            </value>
            <value>
                <fullName>Infectious Disease</fullName>
            </value>
            <value>
                <fullName>Internal Medicine, General</fullName>
            </value>
            <value>
                <fullName>Maternal And Fetal Medicine</fullName>
            </value>
            <value>
                <fullName>Medical Oncology</fullName>
            </value>
            <value>
                <fullName>Midwife</fullName>
            </value>
            <value>
                <fullName>Nephrology</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Nuclear Medicine</fullName>
            </value>
            <value>
                <fullName>Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>Obstetrics/gynecology</fullName>
            </value>
            <value>
                <fullName>Ophthalmology</fullName>
            </value>
            <value>
                <fullName>Orthopedic Surgery</fullName>
            </value>
            <value>
                <fullName>Pediatrics</fullName>
            </value>
            <value>
                <fullName>Physician&apos;s Assistant</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Pulmonary Disease</fullName>
            </value>
            <value>
                <fullName>Radiation Oncology</fullName>
            </value>
            <value>
                <fullName>Radiology</fullName>
            </value>
            <value>
                <fullName>Reproductive Endocrinologist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Contact/fields/ProviderStaffLanguage__c.field-meta.xml
<CustomField>
    <fullName>ProviderStaffLanguage__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Greek</fullName>
            </value>
            <value>
                <fullName>Gujarati</fullName>
            </value>
            <value>
                <fullName>Hebrew</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Hmong</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Persian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Punjabi</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Tagalog</fullName>
            </value>
            <value>
                <fullName>Telugu</fullName>
            </value>
            <value>
                <fullName>Urdu</fullName>
            </value>
            <value>
                <fullName>Vietnamese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Contact/recordTypes/Staff.recordType-meta.xml
<RecordType>
    <fullName>Staff</fullName>
    <active>true</active>
    <label>Staff</label>
</RecordType>

src/orgs/usa/code/query-selectors/classes/StaffQuery.cls
/**
 * @description  : Query object for Staff (Contact) records.
 * @author       : Ivo Rocha
 **/
public inherited sharing class StaffQuery extends QueryObject {
	public StaffQuery() {
		super(
			new List<SObjectField>{
				Contact.Id,
				Contact.OwnerId,
				Contact.RecordTypeId,
				Contact.AccountId,
				Contact.Title,
				Contact.Salutation,
				Contact.FirstName,
				Contact.MiddleName,
				Contact.LastName,
				Contact.Suffix,
				Contact.ProviderMedicalDegree__c, //Is this part of staff too?
				Contact.ProviderSpecialty__c, //Is this part of staff too?
				Contact.ProviderStaffLanguage__c,
				Contact.MailingCountryCode,
				Contact.MailingStateCode,
				Contact.MailingCity,
				Contact.MailingStreet,
				Contact.MailingPostalCode,
				Contact.Phone,
				Contact.MobilePhone,
				Contact.Fax,
				Contact.Email,
				Contact.AdditionalEmail__c
			},
			Contact.SObjectType
		);
		byRecordTypeId(RecordTypes.CONTACT_STAFF.Id);
	}
}