src/orgs/usa/data-model/objects/Contact/fields/ProviderNpi__c.field-meta.xml
<CustomField>
    <fullName>ProviderNpi__c</fullName>
    <label>NPI #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/ApiSchemaSpec__c.field-meta.xml
<CustomField>
    <fullName>ApiSchemaSpec__c</fullName>
    <description>Specifies the API Schema Specifications. Will map to a target class. Eg. if spec is Artemis then a class ArtemisRestClient must exist</description>
    <label>API Schema Spec</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Artemis</fullName>
                <default>true</default>
                <label>Artemis</label>
            </value>
            <value>
                <fullName>Sivis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/InboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>InboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for inbound requests in days. This setting determines how long inbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of inbound requests.</description>
    <inlineHelpText>The number of days to retain logs. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Inbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description>API Name of the Named Credential associated with the EMR Server record, used for authentication purposes.</description>
    <inlineHelpText>Enter the Developer API Name of the Named Credential that will be used for authentication with the EMR Server.</inlineHelpText>
    <label>Named Credential</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/OutboundRequestsRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>OutboundRequestsRetentionPeriod__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Defines the retention period for outbound requests in days. This setting determines how long outbound request records will be retained in the system before being automatically deleted.
Note that a value of &apos;0&apos; or any negative number will be considered as unlimited retention, preventing automatic deletion of outbound requests.</description>
    <inlineHelpText>The number of days to retain requests. A value of &apos;0&apos; or any negative number means unlimited retention.</inlineHelpText>
    <label>Outbound requests retention period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/fields/TimeoutRequestPeriod__c.field-meta.xml
<CustomField>
    <fullName>TimeoutRequestPeriod__c</fullName>
    <defaultValue>60000</defaultValue>
    <inlineHelpText>In milliseconds</inlineHelpText>
    <label>Timeout request after (ms)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/EmrServerContactReference__c.object-meta.xml
<CustomObject>
    <label>EMR Server Contact Reference</label>
    <nameField>
        <displayFormat>ESCR-{0000}</displayFormat>
        <label>EMR Server Contact Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Contact References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>EmrServerContactRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>EMR Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipName>EmrServerContactRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServerContactReference__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Identifier</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/code/modules/artemis-data-processors/classes/tests/ArtemisPractitionersDataProcessorTest.cls
/**
 * @description  : Unit tests for ArtemisPractitionersDataProcessor
 * @author       : Ivo Rocha
 * @testSuite    : ArtemisDataProcessors
 **/
@isTest
private class ArtemisPractitionersDataProcessorTest {
	@TestSetup
	static void makeData() {
		EmrServer__c emrServer = new EmrServer__c(
			Name = 'XPTO',
			ApiSchemaSpec__c = 'XPTO',
			NamedCredential__c = 'https://unit.xpto.test',
			TimeoutRequestPeriod__c = 50000,
			InboundRequestsRetentionPeriod__c = 10,
			OutboundRequestsRetentionPeriod__c = 15
		);
		insert emrServer;

		Contact practitioner = new Contact(RecordTypeId = RecordTypes.CONTACT_PROVIDER.Id, FirstName = 'Foo', LastName = 'Bar', ProviderNpi__c = '1234567890');
		insert practitioner;

		EmrServerContactReference__c emrServerContactReference = new EmrServerContactReference__c(
			EmrServer__c = emrServer.Id,
			Contact__c = practitioner.Id,
			Identifier__c = '1234567890'
		);
		insert emrServerContactReference;
	}

	@isTest
	static void shouldCreateNewPractitioner() {
		EmrServer emrServer = EmrServer.getInstance('XPTO');

		ArtemisPractitionerRestModel payloadModel = new ArtemisPractitionerRestModel();
		payloadModel.id = '1234567890';
		payloadModel.firstName = 'Foo';
		payloadModel.lastName = 'Bar';
		payloadModel.npi = '1234567890';

		ArtemisPractitionersDataProcessor processor = new ArtemisPractitionersDataProcessor();
		processor.add(emrServer, payloadModel);

		Test.startTest();
		List<EmrServerDataProcessRequestResult> results = processor.process();
		Test.stopTest();

		//TODO: final logic when the processor is fully implemented
	}
}