src/global/core-modules/legacy-data-mgmt/objects/LegacyDataEntry__c/LegacyDataEntry__c.object-meta.xml
<CustomObject>
    <description>Object to store legacy data coming from other systems. Records will be attached to single records: Accounts, Contacts, Leads, Appointments, etc.</description>
    <label>Legacy Data Entry</label>
    <nameField>
        <displayFormat>LDE-{0000}</displayFormat>
        <label>Legacy Data Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legacy Data Entries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/legacy-data-mgmt/objects/LegacyDataEntry__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/legacy-data-mgmt/objects/LegacyDataEntry__c/fields/FieldValue__c.field-meta.xml
<CustomField>
    <fullName>FieldValue__c</fullName>
    <label>Value</label>
    <type>TextArea</type>
</CustomField>

src/global/core-modules/legacy-data-mgmt/objects/LegacyDataEntry__c/fields/SourceEntityId__c.field-meta.xml
<CustomField>
    <fullName>SourceEntityId__c</fullName>
    <description>Stores the ID of the source object related to the request.</description>
    <externalId>true</externalId>
    <label>Source Entity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/legacy-data-mgmt/classes/tests/LegacyDataControllerTest.cls
/**
 * @description  : This class is responsible for testing the LegacyDataController class, specifically the getLegacyData method.
 * @author       : Ivo Rocha
 **/
@isTest
private class LegacyDataControllerTest {
	@TestSetup
	static void makeData() {
		// Create a test record for LegacyDataEntry__c
		LegacyDataEntry__c testEntry = new LegacyDataEntry__c(
			FieldName__c = 'TestField',
			FieldValue__c = 'TestValue',
			SourceEntityId__c = '003bc00000FklUjAAJ'
		);
		insert testEntry;
	}

	@isTest
	static void testGetLegacyData() {
		Test.startTest();
		List<LegacyDataEntry__c> result = LegacyDataController.getLegacyData('003bc00000FklUjAAJ');
		Test.stopTest();

		System.assertEquals(1, result.size(), 'Expected one legacy data entry to be returned.');
		System.assertEquals('TestField', result[0].FieldName__c, 'Field names do not match.');
		System.assertEquals('TestValue', result[0].FieldValue__c, 'Field values do not match.');
	}
}