src/global/core-modules/legacy-data-mgmt/objects/LegacyDataEntry__c/LegacyDataEntry__c.object-meta.xml
<CustomObject>
    <description>Object to store legacy data coming from other systems. Records will be attached to single records: Accounts, Contacts, Leads, Appointments, etc.</description>
    <label>Legacy Data Entry</label>
    <nameField>
        <displayFormat>LDE-{0000}</displayFormat>
        <label>Legacy Data Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legacy Data Entries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/legacy-data-mgmt/objects/LegacyDataEntry__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/legacy-data-mgmt/objects/LegacyDataEntry__c/fields/FieldValue__c.field-meta.xml
<CustomField>
    <fullName>FieldValue__c</fullName>
    <label>Value</label>
    <type>TextArea</type>
</CustomField>

src/global/core-modules/legacy-data-mgmt/objects/LegacyDataEntry__c/fields/SourceEntityId__c.field-meta.xml
<CustomField>
    <fullName>SourceEntityId__c</fullName>
    <description>Stores the ID of the source object related to the request.</description>
    <externalId>true</externalId>
    <label>Source Entity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/legacy-data-mgmt/classes/LegacyDataController.cls
/**
 * @description  : This class is responsible for managing legacy data entries in the system, used by the LWC 'legacyDataDisplay' component.
 * @author       : Ivo Rocha
 * @testClass    : LegacyDataControllerTest
 **/
public with sharing class LegacyDataController {
	@AuraEnabled(cacheable=true)
	public static List<LegacyDataEntry__c> getLegacyData(Id recordId) {
		return [SELECT FieldName__c, FieldValue__c FROM LegacyDataEntry__c WHERE SourceEntityId__c = :recordId];
	}
}