src/global/core-modules/leads-mgmt/lead-interactions/objects/LeadInteractionEntry__c/LeadInteractionEntry__c.object-meta.xml
<CustomObject>
    <description>Logs individual interactions with leads, capturing details such as interaction date, type, channel, and comments. This object helps track interactions history without altering the main Lead record.</description>
    <label>Lead Interaction Entry</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>Lead Interaction Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Interaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/global/core-modules/leads-mgmt/lead-interactions/objects/LeadInteractionEntry__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Interaction Entries</relationshipLabel>
    <relationshipName>LeadInteractionEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/global/core-modules/leads-mgmt/lead-interactions/classes/LeadInteractionEntryQuery.cls
/**
 * @description  : Query object for LeadInteractionEntry__c
 * @author       : Ivo Rocha
 * @testClass    : LeadInteractionEntryQueryTest
 **/
public inherited sharing class LeadInteractionEntryQuery extends QueryObject {
	public LeadInteractionEntryQuery() {
		super(LeadInteractionEntry__c.SObjectType);
		withAllFields();
	}

	public LeadInteractionEntryQuery byLeadId(Id leadId) {
		return byLeadId(new Set<Id>{ leadId });
	}

	public LeadInteractionEntryQuery byLeadId(Set<Id> leadIds) {
		return (LeadInteractionEntryQuery) byField(LeadInteractionEntry__c.Lead__c, 'IN', leadIds);
	}
}