src/global/core-modules/leads-mgmt/inbound-leads/objects/InboundLead__c/InboundLead__c.object-meta.xml
<CustomObject>
    <description>This is a temporary storage object designed to capture and hold inbound leads prior to their conversion into official Lead records. This object ensures that every web lead is reliably recorded in the database, providing a buffer against invalid or incomplete data that might otherwise disrupt the standard Lead creation process. By utilizing this object, we can facilitate error handling and review of web leads, ensuring that all submissions are accounted for and processed efficiently, even in cases of data inconsistency.</description>
    <label>Inbound Lead</label>
    <nameField>
        <displayFormat>INL-{0000}</displayFormat>
        <label>Inbound Lead #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Leads</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/InboundLead__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description
	>Cannot be set with the values of &quot;Brand&quot; Global Value Set, otherwise we might get failures if a incorrect Brand is populated in the source. Eventually and error will be thrown due to invalid Brand on Lead object, but Inbound Lead (and must) still successfully created.</description>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RMA</fullName>
                <default>true</default>
                <label>RMA</label>
            </value>
            <value>
                <fullName>Boston IVF</fullName>
            </value>
            <value>
                <fullName>Pearl IVF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Lead/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Boston IVF</fullName>
    </customValue>
    <customValue>
        <fullName>RMA</fullName>
    </customValue>
    <customValue>
        <fullName>Conceptions</fullName>
    </customValue>
    <customValue>
        <fullName>Ovatures</fullName>
    </customValue>
    <customValue>
        <fullName>Peak Men&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Pearl IVF</fullName>
    </customValue>
    <description>Defines the lists of brands that are part of IVIRMA Global.</description>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

src/orgs/usa/code/modules/lead-mgmt/inbound-leads/classes/tests/InboundLeadConversionPluginImplTest.cls
/**
 * @description       : Test class for InboundLeadConversionPluginImpl.
 * @author            : Daniel Belini
 * @testSuite         :
 **/
@IsTest
private class InboundLeadConversionPluginImplTest {
	@isTest
	static void shouldMatchExistingLead() {
		Lead testLead = new Lead(LastName = 'FooBar', Email = 'foo.bar@example.com', Brand__c = 'Boston IVF');
		insert testLead;

		InboundLead__c inboundTestLead = new InboundLead__c(Email__c = 'foo.bar@example.com', Brand__c = 'Boston IVF');
		insert inboundTestLead;

		Test.startTest();
		InboundLeadConversionPluginImpl plugin = new InboundLeadConversionPluginImpl();
		Id foundLeadId = plugin.findExistingMatchingLead(inboundTestLead);
		Test.stopTest();

		Assert.areNotEqual(null, foundLeadId, 'The lead should be found');
		Assert.areEqual(testLead.Id, foundLeadId, 'The lead should be the existing lead');
	}

	@isTest
	static void shouldNotMatchExistingLead() {
		Lead testLead = new Lead(LastName = 'FooBar', Email = 'foo.bar@example.com', Brand__c = 'Boston IVF');
		insert testLead;

		InboundLead__c inboundTestLead = new InboundLead__c(Email__c = 'bar.foo@example.com', Brand__c = 'Boston IVF');
		insert inboundTestLead;

		Test.startTest();
		InboundLeadConversionPluginImpl plugin = new InboundLeadConversionPluginImpl();
		Id foundLeadId = plugin.findExistingMatchingLead(inboundTestLead);
		Test.stopTest();

		Assert.areEqual(null, foundLeadId, 'The lead should not be found');
	}

	@isTest
	static void shouldReopenUnqualifiedLead() {
		Lead testLead = new Lead(LastName = 'FooBar', Email = 'foo.bar@example.com', Brand__c = 'Boston IVF', Status = 'Unqualified');
		insert testLead;

		InboundLead__c inboundTestLead = new InboundLead__c(Email__c = 'foo.bar@example.com', Brand__c = 'Boston IVF');
		insert inboundTestLead;

		Test.startTest();
		InboundLeadConversionPluginImpl plugin = new InboundLeadConversionPluginImpl();
		plugin.postProcess(inboundTestLead, testLead, null, null);
		Test.stopTest();

		Assert.areEqual('New', testLead.Status, 'The lead should be reopened');
	}
}