src/global/core-modules/leads-mgmt/inbound-leads/objects/InboundLead__c/InboundLead__c.object-meta.xml
<CustomObject>
    <description>This is a temporary storage object designed to capture and hold inbound leads prior to their conversion into official Lead records. This object ensures that every web lead is reliably recorded in the database, providing a buffer against invalid or incomplete data that might otherwise disrupt the standard Lead creation process. By utilizing this object, we can facilitate error handling and review of web leads, ensuring that all submissions are accounted for and processed efficiently, even in cases of data inconsistency.</description>
    <label>Inbound Lead</label>
    <nameField>
        <displayFormat>INL-{0000}</displayFormat>
        <label>Inbound Lead #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Leads</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/InboundLead__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description
	>Cannot be set with the values of &quot;Brand&quot; Global Value Set, otherwise we might get failures if a incorrect Brand is populated in the source. Eventually and error will be thrown due to invalid Brand on Lead object, but Inbound Lead (and must) still successfully created.</description>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RMA</fullName>
                <default>true</default>
                <label>RMA</label>
            </value>
            <value>
                <fullName>Boston IVF</fullName>
            </value>
            <value>
                <fullName>Pearl IVF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/orgs/usa/data-model/objects/Lead/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

src/global/core-modules/leads-mgmt/lead-interactions/objects/LeadInteractionEntry__c/LeadInteractionEntry__c.object-meta.xml
<CustomObject>
    <description>Logs individual interactions with leads, capturing details such as interaction date, type, channel, and comments. This object helps track interactions history without altering the main Lead record.</description>
    <label>Lead Interaction Entry</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>Lead Interaction Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Interaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/orgs/usa/data-model/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Boston IVF</fullName>
    </customValue>
    <customValue>
        <fullName>RMA</fullName>
    </customValue>
    <customValue>
        <fullName>Conceptions</fullName>
    </customValue>
    <customValue>
        <fullName>Ovatures</fullName>
    </customValue>
    <customValue>
        <fullName>Peak Men&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Pearl IVF</fullName>
    </customValue>
    <description>Defines the lists of brands that are part of IVIRMA Global.</description>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

src/orgs/usa/code/modules/lead-mgmt/inbound-leads/classes/InboundLeadConversionPluginImpl.cls
/**
 * @description  : This plugin is used to find an existing matching lead and perform post-processing on the inbound lead after it has been converted to a lead and/or a lead interaction entry. Overrides the default behavior of the InboundLeadConversion class.
 * @author       : Daniel Belini
 **/
public with sharing class InboundLeadConversionPluginImpl implements InboundLeadConversion.IPluginMatchingLead, InboundLeadConversion.IPluginPostProcessing {
	public Id findExistingMatchingLead(InboundLead__c inboundLead) {
		return Query.of(
				[
					SELECT Id
					FROM Lead
					WHERE Email = :inboundLead.Email__c AND Brand__c = :inboundLead.Brand__c AND IsConverted = FALSE
					LIMIT 1
				]
			)
			.getFirstIdOrNull();
	}

	public void postProcess(InboundLead__c inboundLead, Lead lead, LeadInteractionEntry__c leadInteractionEntry, CampaignMember campaignMemberRecord) {
		//If the lead already exists and its status is 'Unqualified', we need to "reopen it" by setting the status to 'New'
		if (lead.Id != null && lead.Status == 'Unqualified') {
			lead.Status = 'New';
		}
	}
}