src/global/core-modules/leads-mgmt/inbound-leads/objects/InboundLead__c/InboundLead__c.object-meta.xml
<CustomObject>
    <description>This is a temporary storage object designed to capture and hold inbound leads prior to their conversion into official Lead records. This object ensures that every web lead is reliably recorded in the database, providing a buffer against invalid or incomplete data that might otherwise disrupt the standard Lead creation process. By utilizing this object, we can facilitate error handling and review of web leads, ensuring that all submissions are accounted for and processed efficiently, even in cases of data inconsistency.</description>
    <label>Inbound Lead</label>
    <nameField>
        <displayFormat>INL-{0000}</displayFormat>
        <label>Inbound Lead #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Leads</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/global/core-modules/leads-mgmt/inbound-leads/objects/InboundLead__c/fields/AddressStateCode__c.field-meta.xml
<CustomField>
    <fullName>AddressStateCode__c</fullName>
    <label>Address State Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/leads-mgmt/lead-interactions/objects/LeadInteractionEntry__c/LeadInteractionEntry__c.object-meta.xml
<CustomObject>
    <description>Logs individual interactions with leads, capturing details such as interaction date, type, channel, and comments. This object helps track interactions history without altering the main Lead record.</description>
    <label>Lead Interaction Entry</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>Lead Interaction Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Interaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/global/core-modules/leads-mgmt/inbound-leads-convert-process/classes/tests/FlowAction_ProcessInboundLeadsTest.cls
/**
 * @description  : Test class for FlowAction_ProcessInboundLeads.
 * @author       : Ivo Rocha
 * @testSuite    : InboundLeadsProcessing
 **/
@isTest
private class FlowAction_ProcessInboundLeadsTest {
	@isTest
	private static void testProcess() {
		InboundLead__c inboundLead = new InboundLead__c(
			Email__c = 'john.doe@example.com',
			FirstName__c = 'John',
			LastName__c = 'Doe',
			AddressStateCode__c = 'NY'
		);
		insert inboundLead;

		Test.startTest();
		FlowAction_ProcessInboundLeads.process(new List<Id>{ inboundLead.Id });
		Test.stopTest();

		Assert.areEqual(1, [SELECT COUNT() FROM Lead], 'One lead should be created');
		Assert.areEqual(1, [SELECT COUNT() FROM LeadInteractionEntry__c], 'One lead interaction entry should be created');
	}
}