src/orgs/usa/data-model/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Appointment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/Appointment__c/fields/AppointmentDateTime__c.field-meta.xml
<CustomField>
    <fullName>AppointmentDateTime__c</fullName>
    <label>Appointment Date Time</label>
    <type>DateTime</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/AppointmentType__c.field-meta.xml
<CustomField>
    <fullName>AppointmentType__c</fullName>
    <label>Appointment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/CalendarName__c.field-meta.xml
<CustomField>
    <fullName>CalendarName__c</fullName>
    <label>Calendar Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/EmrAppointmentId__c.field-meta.xml
<CustomField>
    <fullName>EmrAppointmentId__c</fullName>
    <externalId>true</externalId>
    <label>Artemis Appointment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>Artemis Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>EmrServerAppointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Location account record.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IVIRMA Location Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>LocationAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>PatientAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Provider contact record.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>ProviderAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/RawLocationId__c.field-meta.xml
<CustomField>
    <fullName>RawLocationId__c</fullName>
    <description>Raw location Id received on the payload. To be stored separately in case the matching location does not exist in the system (yet?) and later can be correctly assigned upon its creation.</description>
    <label>Raw Location Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/RawPatientId__c.field-meta.xml
<CustomField>
    <fullName>RawPatientId__c</fullName>
    <description>Raw provider Id received on the payload. To be stored separately in case the matching patient does not exist in the system (yet?) and later can be correctly assigned upon its creation.</description>
    <label>Raw Patient Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/RawProviderId__c.field-meta.xml
<CustomField>
    <fullName>RawProviderId__c</fullName>
    <description>Raw provider Id received on the payload. To be stored separately in case the matching provider does not exist in the system (yet?) and later can be correctly assigned upon its creation.</description>
    <label>Raw Provider Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/orgs/usa/code/query-selectors/classes/AppointmentQuery.cls
/**
 * @description  : Query object for Appointment__c records.
 * @author       : Ivo Rocha
 **/
public inherited sharing class AppointmentQuery extends QueryObject {
	public AppointmentQuery() {
		super(
			new List<SObjectField>{
				Appointment__c.Id,
				Appointment__c.Name,
				Appointment__c.EmrAppointmentId__c,
				Appointment__c.EmrServer__c,
				Appointment__c.Patient__c,
				Appointment__c.Status__c,
				Appointment__c.CalendarName__c,
				Appointment__c.Provider__c,
				Appointment__c.Location__c,
				Appointment__c.AppointmentType__c,
				Appointment__c.AppointmentDateTime__c,
				Appointment__c.RawProviderId__c,
				Appointment__c.RawLocationId__c,
				Appointment__c.RawPatientId__c
				//TODO: Remaining fields
			},
			Appointment__c.SObjectType
		);
	}

	public AppointmentQuery byEmrServerId(Id serverId) {
		return byEmrServerId(new Set<Id>{ serverId });
	}

	public AppointmentQuery byEmrServerId(Set<Id> serverIds) {
		return (AppointmentQuery) byField(Appointment__c.EmrServer__c, 'IN', serverIds);
	}

	public AppointmentQuery byExternalId(String externalId) {
		return byExternalId(new Set<String>{ externalId });
	}

	public AppointmentQuery byExternalId(Set<String> externalIds) {
		return (AppointmentQuery) byField(Appointment__c.EmrAppointmentId__c, 'IN', externalIds);
	}

	public AppointmentQuery byPatientId(Id patientId) {
		return byPatientId(new Set<Id>{ patientId });
	}

	public AppointmentQuery byPatientId(Set<Id> patientIds) {
		return (AppointmentQuery) byField(Appointment__c.Patient__c, 'IN', patientIds);
	}
}