src/orgs/usa/data-model/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Appointment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/Appointment__c/fields/EmrAppointmentId__c.field-meta.xml
<CustomField>
    <fullName>EmrAppointmentId__c</fullName>
    <externalId>true</externalId>
    <label>Artemis Appointment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/EmrServer__c.field-meta.xml
<CustomField>
    <fullName>EmrServer__c</fullName>
    <label>Artemis Server</label>
    <referenceTo>EmrServer__c</referenceTo>
    <relationshipLabel>EmrServerAppointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>PatientAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/ScheduledBy__c.field-meta.xml
<CustomField>
    <fullName>ScheduledBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SchedulerAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/ArtemisChangeEvent__e/ArtemisChangeEvent__e.object-meta.xml
<CustomObject>
    <description>Platform Event object used to receive published events by the Artemis EMR servers, whenever modifications happen in the system and changes must be communicated back to Salesforce.</description>
    <label>Artemis Change Event</label>
    <pluralLabel>Artemis Change Events</pluralLabel>
</CustomObject>

src/orgs/usa/data-model/objects/ArtemisChangeEvent__e/fields/ArtemisServer__c.field-meta.xml
<CustomField>
    <fullName>ArtemisServer__c</fullName>
    <description>Defines the source Artemis server instance this event was generated from. Expected values are: BOSNY, BOSNE and BOSNC</description>
    <label>Artemis Server</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/ArtemisChangeEvent__e/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>The type of event that affected the resource. Expects values like: create, update and delete.</description>
    <label>Event</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/ArtemisChangeEvent__e/fields/ResourceIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ResourceIdentifier__c</fullName>
    <description>External identifier of the affected resource.</description>
    <label>Resource Identifier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/ArtemisChangeEvent__e/fields/ResourceName__c.field-meta.xml
<CustomField>
    <fullName>ResourceName__c</fullName>
    <description>Name of the affected resource. Expects names like: Patient, Provider, Location, Appointment, ...</description>
    <label>Resource type name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/global/core-modules/emr-server-mgmt/objects/EmrServer__c/EmrServer__c.object-meta.xml
<CustomObject>
    <label>EMR Server</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMR Servers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/orgs/usa/code/modules/artemis-flow-actions/classes/appointments/FlowAction_ArtemisAppointmentsCreate.cls
/**
 * @description  : Allows to create a new appointment in Artemis from Flows
 * @author       : Ivo Rocha
 * @testSuite    :
 * @testClass    :
 **/
public with sharing class FlowAction_ArtemisAppointmentsCreate {
	/**
	 * @description  : Creates a new appointment in Artemis
	 * @param        : List<FlowAction_ArtemisAppointmentsCreateRequest> requests
	 * @return       : List<FlowAction_ArtemisAppointmentsCreateResponse> A response for each request
	 */
	@InvocableMethod(
		label='Create an appointment in Artemis'
		description='Create an appointment in Artemis'
		category='Artemis REST Client'
		iconName='slds:standard:invocable_action'
	)
	public static List<FlowAction_ArtemisAppointmentsCreateResponse> createAppointment(List<FlowAction_ArtemisAppointmentsCreateRequest> requests) {
		List<FlowAction_ArtemisAppointmentsCreateResponse> appointmentResults = new List<FlowAction_ArtemisAppointmentsCreateResponse>();
		List<Appointment__c> appointmentsToCreate = new List<Appointment__c>();

		for (FlowAction_ArtemisAppointmentsCreateRequest request : requests) {
			ArtemisRestClient restClient = (ArtemisRestClient) EmrRestClientFactory.getRestClientInstance(request.emrServerId);

			FlowAction_ArtemisAppointmentsCreateResponse requestResponse = new FlowAction_ArtemisAppointmentsCreateResponse();
			requestResponse.emrServerId = request.emrServerId;
			requestResponse.newAppointmentData = request.appointment;
			try {
				ArtemisAppointmentRestModel response = restClient.appointments.createAppointment(request.appointment);
				requestResponse.appointment = response;
				requestResponse.isSuccess = true;

				// we could create the appointment record directly here using its data processor, but to avoid the overhead of the data processor, we will create the appointment record just with the basic data.
				// and then we will force the update of the appointment record later via Platform Event - just as like as if the EMR Server created it
				requestResponse.appointmentRecord = new Appointment__c(
					Patient__c = request.patientAccountId,
					EmrAppointmentId__c = response.id,
					EmrServer__c = request.emrServerId,
					ScheduledBy__c = UserInfo.getUserId() //TODO: Artemis should provide the user reference instead...
				);
				appointmentsToCreate.add(requestResponse.appointmentRecord);
			} catch (ArtemisRestClientApiErrorException e) {
				requestResponse.isSuccess = false;
				requestResponse.errorMessage = e.getMessage();
				requestResponse.errorResponse = e.getResponse();
			} catch (Exception e) {
				requestResponse.isSuccess = false;
				requestResponse.errorMessage = e.getMessage();
			}
			appointmentResults.add(requestResponse);
		}

		if (!appointmentsToCreate.isEmpty()) {
			insert appointmentsToCreate;

			for (FlowAction_ArtemisAppointmentsCreateResponse response : appointmentResults) {
				response.appointmentId = response.appointmentRecord?.Id;

				// Force the update of the appointment record, as if it was created by the EMR Server
				EventBus.publish(
					new ArtemisChangeEvent__e(
						ArtemisServer__c = response.emrServerId,
						Event__c = 'create',
						ResourceIdentifier__c = response.appointment.id,
						ResourceName__c = 'appointment'
					)
				);
			}
		}

		return appointmentResults;
	}

	public class FlowAction_ArtemisAppointmentsCreateRequest {
		@InvocableVariable(label='Artemis Server Id' description='Artemis Server Id' required=true)
		public String emrServerId;

		@InvocableVariable(label='Appointment' description='Appointment data' required=true)
		public ArtemisNewAppointmentRestModel appointment;

		@InvocableVariable(label='Patient Account Id' description='Patient Account Id' required=true)
		public String patientAccountId;
	}

	public class FlowAction_ArtemisAppointmentsCreateResponse {
		@InvocableVariable(label='Appointment' description='Created appointment data, only returned if the request is successful')
		public ArtemisAppointmentRestModel appointment;

		@InvocableVariable(label='Appointment Id' description='Appointment Id')
		public Id appointmentId;

		@InvocableVariable(label='New Appointment data' description='New appointment data used for the appointment creation')
		public ArtemisNewAppointmentRestModel newAppointmentData;

		//Internal use only - will not be returned to the flow
		public Appointment__c appointmentRecord;

		@InvocableVariable(label='Artemis Server Id' description='Artemis Server Id' required=true)
		public String emrServerId;

		@InvocableVariable(label='Is Success' description='Is Success')
		public Boolean isSuccess;

		@InvocableVariable(label='Error Message' description='Error Message')
		public String errorMessage;

		@InvocableVariable(label='Error Response' description='In case of an error from the Artemis API, the error response will be returned')
		public ArtemisErrorResponseRestModel errorResponse;
	}
}