src/orgs/usa/data-model/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Appointment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/Appointment__c/fields/AppointmentComment__c.field-meta.xml
<CustomField>
    <fullName>AppointmentComment__c</fullName>
    <label>Appointment Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/AppointmentDateTime__c.field-meta.xml
<CustomField>
    <fullName>AppointmentDateTime__c</fullName>
    <label>Appointment Date Time</label>
    <type>DateTime</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/AppointmentType__c.field-meta.xml
<CustomField>
    <fullName>AppointmentType__c</fullName>
    <label>Appointment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/CalendarName__c.field-meta.xml
<CustomField>
    <fullName>CalendarName__c</fullName>
    <label>Calendar Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/CancelationDateTime__c.field-meta.xml
<CustomField>
    <fullName>CancelationDateTime__c</fullName>
    <label>Cancelation Date Time</label>
    <type>DateTime</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/CancelReason__c.field-meta.xml
<CustomField>
    <fullName>CancelReason__c</fullName>
    <label>Cancel Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/ConfirmationDateTime__c.field-meta.xml
<CustomField>
    <fullName>ConfirmationDateTime__c</fullName>
    <label>Confirmation Date Time</label>
    <type>DateTime</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/ConfirmationStatus__c.field-meta.xml
<CustomField>
    <fullName>ConfirmationStatus__c</fullName>
    <label>Confirmation Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/CptCode__c.field-meta.xml
<CustomField>
    <fullName>CptCode__c</fullName>
    <label>CPT Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/EmrAppointmentId__c.field-meta.xml
<CustomField>
    <fullName>EmrAppointmentId__c</fullName>
    <externalId>true</externalId>
    <label>Artemis Appointment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Location account record.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IVIRMA Location Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>LocationAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>PatientAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Provider contact record.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>ProviderAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/RawLocationId__c.field-meta.xml
<CustomField>
    <fullName>RawLocationId__c</fullName>
    <description>Raw location Id received on the payload. To be stored separately in case the matching location does not exist in the system (yet?) and later can be correctly assigned upon its creation.</description>
    <label>Raw Location Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/RawPatientId__c.field-meta.xml
<CustomField>
    <fullName>RawPatientId__c</fullName>
    <description>Raw provider Id received on the payload. To be stored separately in case the matching patient does not exist in the system (yet?) and later can be correctly assigned upon its creation.</description>
    <label>Raw Patient Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/RawProviderId__c.field-meta.xml
<CustomField>
    <fullName>RawProviderId__c</fullName>
    <description>Raw provider Id received on the payload. To be stored separately in case the matching provider does not exist in the system (yet?) and later can be correctly assigned upon its creation.</description>
    <label>Raw Provider Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/ScheduledBy__c.field-meta.xml
<CustomField>
    <fullName>ScheduledBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SchedulerAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/ScheduledDateTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDateTime__c</fullName>
    <label>Scheduled Date Time</label>
    <type>DateTime</type>
</CustomField>

src/orgs/usa/data-model/objects/Appointment__c/fields/SigninFlag__c.field-meta.xml
<CustomField>
    <fullName>SigninFlag__c</fullName>
    <label>Signin Flag</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/code/modules/artemis-rest-client/classes/models/ArtemisAppointmentRestModel.cls
/**
 * @description  : This class represents an appointment in the Artemis Rest API.
 * @author       : Ivo Rocha
 **/
public class ArtemisAppointmentRestModel extends EmrRestClient.RestModel {
	@InvocableVariable
	@AuraEnabled
	public String id;

	@InvocableVariable
	@AuraEnabled
	public String patientId;

	@InvocableVariable
	@AuraEnabled
	public String providerId;

	@InvocableVariable
	@AuraEnabled
	public String locationId;

	@InvocableVariable
	@AuraEnabled
	public String appointmentType;

	@InvocableVariable
	@AuraEnabled
	public String appointmentStatus;

	@InvocableVariable
	@AuraEnabled
	public DateTime appointmentDateTime;

	@InvocableVariable
	@AuraEnabled
	public Long duration;

	@InvocableVariable
	@AuraEnabled
	public String status;

	@InvocableVariable
	@AuraEnabled
	public String confirmationStatus;

	@InvocableVariable
	@AuraEnabled
	public String statusReason;

	@InvocableVariable
	@AuraEnabled
	public String scheduledBy;

	@InvocableVariable
	@AuraEnabled
	public DateTime scheduledDateTime;

	@InvocableVariable
	@AuraEnabled
	public String cptCode;

	/**
	 * @description  : Converts the current ArtemisAppointmentRestModel instance to an Appointment__c object record.
	 * @return Appointment__c A new Appointment__c object record.
	 */
	public Appointment__c toSObject() {
		return toSObject(null, null);
	}

	/**
	 * @description  : Converts the current ArtemisAppointmentRestModel instance to an Appointment__c object record.
	 * @param recordId The Id of the Appointment__c object record, if existing.
	 * @return Appointment__c A new Appointment__c object record.
	 */
	public Appointment__c toSObject(Id recordId) {
		return toSObject(recordId, null);
	}

	/**
	 * @description  : Converts the current ArtemisAppointmentRestModel instance to an Appointment__c object record.
	 * @param contextRefs The context references for the Appointment__c object record.
	 * @return Appointment__c A new Appointment__c object record.
	 */
	public Appointment__c toSObject(ToSObjectContextRefs contextRefs) {
		return toSObject(null, contextRefs);
	}

	/**
	 * @description  : Converts the current ArtemisAppointmentRestModel instance to an Appointment__c object record.
	 * @param recordId The Id of the Appointment__c object record, if existing.
	 * @param contextRefs The context references for the Appointment__c object record.
	 * @return Appointment__c A new Appointment__c object record.
	 */
	public Appointment__c toSObject(Id recordId, ToSObjectContextRefs contextRefs) {
		Appointment__c appointment = new Appointment__c(Id = recordId);
		appointment.EmrAppointmentId__c = this.id;
		appointment.AppointmentComment__c = null; //TODO
		appointment.AppointmentDateTime__c = this.appointmentDateTime;
		appointment.AppointmentType__c = this.appointmentType;
		appointment.CalendarName__c = null; //TODO
		appointment.CancelationDateTime__c = null; //TODO
		appointment.CancelReason__c = null; //TODO
		appointment.ConfirmationDateTime__c = null; //TODO
		appointment.CptCode__c = this.cptCode;
		appointment.ScheduledDateTime__c = this.scheduledDateTime;
		appointment.SigninFlag__c = null;
		appointment.Status__c = this.appointmentStatus;
		appointment.ConfirmationStatus__c = this.confirmationStatus;

		appointment.RawProviderId__c = this.providerId;
		appointment.Provider__c = contextRefs?.sfProviderId;

		appointment.RawPatientId__c = this.patientId;
		appointment.Patient__c = contextRefs?.sfPatientId;

		appointment.RawLocationId__c = this.locationId;
		appointment.Location__c = contextRefs?.sfLocationId;

		//appointment.RawScheduledBy__c = this.scheduledBy;
		//appointment.ScheduledBy__c = contextRefs?.sfScheduledById;

		return appointment;
	}

	public class ToSObjectContextRefs {
		public Id sfLocationId { get; set; }
		public Id sfPatientId { get; set; }
		public Id sfProviderId { get; set; }
		public Id sfScheduledById { get; set; }
	}
}