src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/EmrServerReferralSourceMetadata__c.object-meta.xml
<CustomObject>
    <label>EMR Server Referral Source Metadata</label>
    <nameField>
        <displayFormat>ESRS-{0000}</displayFormat>
        <label>EMR Server Referral Source Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMR Server Referral Sources Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferralCategory__c.field-meta.xml
<CustomField>
    <fullName>ReferralCategory__c</fullName>
    <label>Referral Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferralCategoryInternalId__c.field-meta.xml
<CustomField>
    <fullName>ReferralCategoryInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Referral Category Internal Id</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferralSourceInternalId__c.field-meta.xml
<CustomField>
    <fullName>ReferralSourceInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Referral Source Internal Id (REF)</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/orgs/usa/data-model/objects/EmrServerReferralSourceMetadata__c/fields/ReferredBy__c.field-meta.xml
<CustomField>
    <fullName>ReferredBy__c</fullName>
    <label>Referred By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/orgs/usa/code/modules/artemis-rest-client/classes/models/ArtemisMetadataReferralSourceRestModel.cls
/**
 * @description  : This class represents the metadata referral source model for the EMR Artemis Rest API.
 * @author       : Ivo Rocha
 **/
public class ArtemisMetadataReferralSourceRestModel extends EmrRestClient.RestModel {
	public String id { get; set; }
	public String refBy { get; set; }
	public ReferenceCategory refCat { get; set; }

	public ArtemisMetadataReferralSourceRestModel() {
	}

	public EmrServerReferralSourceMetadata__c toSObject() {
		return toSObject(null);
	}

	public EmrServerReferralSourceMetadata__c toSObject(Id recordId) {
		EmrServerReferralSourceMetadata__c refSourceMetadataRecord = new EmrServerReferralSourceMetadata__c(Id = recordId);
		refSourceMetadataRecord.ReferralSourceInternalId__c = this.id;
		refSourceMetadataRecord.ReferredBy__c = this.refBy;
		refSourceMetadataRecord.ReferralCategory__c = this.refCat?.name;
		refSourceMetadataRecord.ReferralCategoryInternalId__c = this.refCat?.id;
		return refSourceMetadataRecord;
	}

	public Boolean equals(EmrServerReferralSourceMetadata__c refSourceMetadata) {
		return refSourceMetadata != null &&
			this.refCat != null &&
			this.refCat.name == refSourceMetadata.ReferralCategory__c &&
			this.refCat.id == refSourceMetadata.ReferralCategoryInternalId__c &&
			this.id == refSourceMetadata.ReferralSourceInternalId__c &&
			this.refBy == refSourceMetadata.ReferredBy__c;
	}

	public class ReferenceCategory {
		public String id { get; set; }
		public String name { get; set; }
	}
}